### ISSUE TITLE
Help with mod config.

### ISSUE THREAD

**Issue by SheroxGG** [RakambdaOrg/FallingTree#10]
Hello! I downloaded this mod for my server, and I have too many type of axes and too many types of wood. I was wondering if it is possible to make all axes usable on all types of wood. I have seen the config file, but it looks to hard to modify, and I am not an expert on config. Hope you can help. Thanks!!

**Comment by Rakambda** [comment]
For the config file: You have to modify the `tools => whitelisted` and `trees => logs_blacklisted`.
If you never modified them they should look like `[]` (empty list). 
You simply have to add every item/block to the list with their ID, separated by commas. 
So it should look like `["minecraft:oak_wood", "minecraft:my_custom_wood"]`. 

To see these IDs you can press F3+H and when you over an item it'll be displayed in gray.

 ---

Another way of doing this is to indicate to the game that the tools are axes and the blocks logs.
If this isn't your mod, you'll have to request the author to add the appropriate tags.

If you made them, you'll have to add them to the tags yourself either in the mod directly, or by doing a datapack.

`data/minecraft/tags/blocks/logs.json`:
```json
{
	"values":	[
		"minecraft:wood_1",
		"minecraft:wood_2",
		"minecraft:wood_3"
	]
}
```
And do a similar thing for `data/minecraft/tags/blocks/leaves.json`

**Comment by SheroxGG** [comment]
![image](https://user-images.githubusercontent.com/34599826/81461484-7580d000-91ac-11ea-9a0b-ce553a427916.png)
![image](https://user-images.githubusercontent.com/34599826/81461488-7e71a180-91ac-11ea-8f2b-7b9e4b9aa7f6.png)
Thanks for the help! Is it like this? Ive tried this but it isnt working. Any idea? Thanks!

**Comment by Rakambda** [comment]
Seems like you're in `1.12`. The configuration file format is a bit different in this one. As you can see there is angle brackets, and these are the delimiters for the list (instead of `[]` for 1.14+).

I can't test it right now and am not really familiar with this version, but I guess it should should look a bit like this:
```cfg
S:whitelisted <
    aaaa:bbbbb
    aaaa:cccccc
>
```
