### ISSUE TITLE
FallingTree mod doesn't work

### ISSUE THREAD

**Issue by AnpyHelp** [RakambdaOrg/FallingTree#101]
**FallingTree mod doesn't work**

**To Reproduce**
1. I added some mods. FallingTree mod stopped working. Help me please. I tried to change versions of the mod, but it doesn't help. I haven't ever opened the mod's config. I don't know the reason. Do you know some mods that could broke the mod?

**Infos:**
 - Minecraft version: [e.g. 1.16.5]
 - Mod version: [e.g. 2.11.3]
 - Forge version: [forge minecraft 1.16.5 tlauncher]

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

**Comment by Rakambda** [comment]
Do you have a log file to provide (latest.log or debug.log in the logs folder) ? Just like that it's quite hard to tell.

**Comment by AnpyHelp** [comment]
> Do you have a log file to provide (latest.log or debug.log in the logs folder) ? Just like that it's quite hard to tell.

Do you have a discord? I can show you

**Comment by Rakambda** [comment]
`RakSrinaNa#4089` but just as a way to send the log file. I won't do any support directly on it, I prefer that it is logged here so other people can refer to it if needed.

**Comment by Rakambda** [comment]
Incompatibility due to Personality mod version 1.0.1. Version 1.0.2 fixed that issue.
