### ISSUE TITLE
Compat w/ Project MMO

### ISSUE THREAD

**Issue by WenXin20** [RakambdaOrg/FallingTree#11]
**Describe the bug**
Project MMO allows the player to gain woodcutting stats when chopping down trees. 
But if I use this mod to cut trees, no stats are gained. The mod dev said the proper events are not being sent.

**To Reproduce**
1. Install Project MMO
2. Chop down trees both with and without Falling Tree.

**Infos:**
 - Minecraft verson: 1.15.2
 - Mod version: 2.1.3+28
 - [Project MMO](https://www.curseforge.com/minecraft/mc-mods/project-mmo)  version: 2.42

**Comment by Rakambda** [comment]
Are they really meant to be compatible between each others? I don't know MMO at all but from what I read it supports wood cutting and have the option "Vein Mining". So it should achieve the same as this mod no?

**Comment by WenXin20** [comment]
I suppose so. But I do prefer using a tree chopper mod instead of vein mining. This is mainly for my server modpack that I am building.

**Comment by Rakambda** [comment]
Can you try with this version? https://github.com/RakSrinaNa/FallingTree/releases/tag/1.15.2-2.1.4b1

I think it should make MMO able to gather the stats you want. Though only 1 block will be counter per tree chopped down (as the other blocks of the tree are cut by the server and not the player).

**Comment by WenXin20** [comment]
Sure! I'll give it a try later today.

**Comment by WenXin20** [comment]
Yep, it works on the first block as you said. Thanks
