### ISSUE TITLE
Doesn't work on small server within a modpack

### ISSUE THREAD

**Issue by FuryOfOlympus** [RakambdaOrg/FallingTree#113]
**Describe the bug**
I am using the Fabric of Life modpack, but when I try to use this on a server this mod stops working. 
Does anyone have an idea of how this might happen?
It does work on a single player instance, and the mod is installed on the server. 

**To Reproduce**
1. Load the Fabric of Life modpack on a server
2. Fail

**Infos:**
 - Minecraft version: 1.16.5
 - Mod version: 2.11.4
 - Fabric version: I don't actually know, nor know how to find out

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

**Comment by Rakambda** [comment]
Can't reproduce with just FallingTree.

Either:
* You have a configuration on the server that deactivate the tree breaking / invert sneak / ....
* One of the other mods makes it incompatible server-side

If this is the latter I'll be long to find with pair of mods brings the problem. The easiest is to shrink the mods by 2 each time.
So for example:
* Start minecraft with half the mods (FT included), if it bugs, then the pair of mods is in that half list. Other wise it is in the other.
* Keep only the half that has the incompatible mod (and always keep FT)
* Repeat

If you have 100 mods, repeating these steps 7 times should be enough to find the 2 mods that together are incompatible.
