### ISSUE TITLE
Mod won't cut down any tree

### ISSUE THREAD

**Issue by TGDJ** [RakambdaOrg/FallingTree#128]
**Describe the bug**
Mod will not cut down any tree, I tried messing with the config but still wont work.

**Infos:**
 - Minecraft version: 1.17
 - Mod version:      2.11.4
 - Fabric version:   0.34.10+1.17

**Comment by Rakambda** [comment]
I can't reproduce. Maybe you can share your config and explain a bit more what game mode you're in, what tool you use etc ?

**Comment by TGDJ** [comment]
Using an Axe, any axe stone Iron wood etc. On survival Minecraft realms 
{
	// When set to true, a tree will only be chopped down if the player is sneaking.
	"reverseSneaking": false,
	// When set to true, the mod will cut down trees in creative too.
	"breakInCreative": false,
	"trees": {
		/* Additional list of blocks considered as logs and that will be destroyed by the mod. 
		   INFO: Blocks marked with the log tag will already be whitelisted.
		*/
		"whitelistedLogs": [],
		/* List of blocks that should not be considered as logs. 
		   INFO: This wins over the whitelist.
		*/
		"blacklistedLogs": [],
		/* Additional list of blocks considered as leaves (decay naturally). 
		   INFO: Blocks marked with the leaves tag will already be whitelisted.
		*/
		"whitelistedLeaves": [],
		// Additional list of blocks considered as leaves but that doesn't decay (need to be broken by tool).
		"whitelistedNonDecayLeaves": [],
		/* List of blocks that should not be considered as leaves. 
		   INFO: This wins over the whitelist.
		*/
		"blacklistedLeaves": [],
		/* How to break the tree. 
		   INSTANTANEOUS will break it in one go. 
		   SHIFT_DOWN will make the tree fall down as you cut it, so you still have to break x blocks but don't have to climb the tree for them.
		*/
		"breakMode": "INSTANTANEOUS",
		/* What part of the tree should be cut. 
		   WHOLE_TREE will break the whole tree. 
		   ABOVE_CUT will break only blocks that are connected from above the cut point. 
		   ABOVE_Y will break only blocks that are above the y value of the cut point.
		*/
		"detectionMode": "WHOLE_TREE",
		/* The maximum size of a tree. If there's more logs than this value the tree won't be cut. 
		   INFO: Only in INSTANTANEOUS mode.
		*/
		"maxSize": 100,
		/* The minimum amount of leaves that needs to be around the top most log in order for the mod to consider it a tree. 
		   INFO: Only in INSTANTANEOUS mode.
		*/
		"minimumLeavesAroundRequired": 1,
		// When set to true, the mod be applied when cutting trunks.
		"treeBreaking": true,
		// When set to true, leaves that should naturally break will be broken instantly.
		"leavesBreaking": true,
		/* Radius to force break leaves. If another tree is still holding the leaves they'll still be broken. If the leaves are persistent (placed by player) they'll also be destroyed. 
		   The radius is applied from one of the top most log blocks. 
		   INFO: break_leaves must be activated for this to take effect. 
		   INFO: Only in INSTANTANEOUS mode.
		*/
		"leavesBreakingForceRadius": 0,
		/* When set to true this allow to have any kind of log in a tree trunk. 
		   Otherwise (false) the trunk will be considered as being only one kind of log.
		*/
		"allowMixedLogs": false,
		// When set to true nether tree warts (leaves) will be broken along with the trunk.
		"breakNetherTreeWarts": true,
		/* This defines the area in which the tree is searched. If any branch is going out of this area it won't be cut. 
		   This value is the radius of the area. 
		   i.e. Setting a value of 2 will result on an area of 3x3 centered on the log broken. 
		   If this value is set to a negative number then no area restriction will be applied.
		*/
		"searchAreaRadius": -1,
		/* List the blocks that can be against the tree. If something else is adjacent then the tree won't be cut. 
		   INFO: Use adjacentStopMode to define how we stop the search for the tree.
		*/
		"whitelistedAdjacentBlocks": [],
		/* What to do when an non whitelisted adjacent block is found. 
		   STOP_ALL will stop the search and nothing will be cut. 
		   STOP_BRANCH will stop the current branch only. The rest of the tree will be cut.
		*/
		"adjacentStopMode": "STOP_ALL"
	},
	"tools": {
		/* Additional list of tools that can be used to chop down a tree. 
		   INFO: Items marked with the axe tag will already be whitelisted.
		*/
		"whitelisted": [],
		/* List of tools that should not be considered as tools. 
		   INFO: This wins over the whitelist.
		*/
		"blacklisted": [],
		// When set to true, when a tree is broken and the tool is about to break we will just break enough blocks so that the tool is left at 1 of durability.
		"preserve": false,
		/* When set to true, the mod will be activated no matter what you have in your hand (or empty hand). 
		   INFO: Blacklist still can be use to restrict some tools.
		*/
		"ignoreTools": false,
		/* Defines the number of times the damage is applied to the tool. 
		   ie: if set to 1 then breaking 5 logs will give 5 damage. 
		   ie: if set to 2 then breaking 5 logs will give 10 damage. 
		   If set to 0, it'll still apply 1 damage for every cut. 
		   INFO: This only applies when the tree is cut when using the mod.
		*/
		"damageMultiplicand": 1,
		/* Applies a speed modifier when breaking the tree. 
		   0 will disable this, so the speed will be the default one of breaking a block. 
		   If set to 1 each log block will be counted once, so if the tree is 5 blocks tall it'll require the time of breaking 5 logs. 
		   If set to 2 each log block will be counted twice, so if the tree is 5 blocks tall, it'll require the time of breaking 10 logs. 
		   INFO: Only in INSTANTANEOUS mode. 
		   WARNING: If you are on a server, this either has to be set to 0 or every player should have the mod. Else they'll have a weird effect of breaking the block but the block is still there.
		*/
		"speedMultiplicand": 0.0
	}
}

**Comment by Rakambda** [comment]
If playing on a server then the mod needs to be installed server side.

I don't really know how realms work but I think it isn't possible to install mods there.
