### ISSUE TITLE
Tooltip for Max tree size false information

### ISSUE THREAD

**Issue by goodideagiver** [RakambdaOrg/FallingTree#129]
**Describe the bug**
 
Max tree size config option restricts `shift down` mode, but tooltip specifically says it's only for `instant` mode

**To Reproduce**
https://streamable.com/1tum4r

**Infos:**
 - Minecraft version:     1.16.5
 - Mod version:            2.11.4
 - Fabric API version:     0.34.6

**Comment by Rakambda** [comment]
You're right. I think i'll just remove the text in the tooltip and make it apply to both (like now).

I changed the way it was done some time ago and is actually now performed when the tree is "detected" to avoid lags if lots of trees are touching in a dense forest. So if you play with other mods that have larger trees you'll have to bump up a bit the max size value like you did.

Thanks for the info about the wrong tooltip tho !
