### ISSUE TITLE
Tree leaves

### ISSUE THREAD

**Issue by Roll4Ignition** [RakambdaOrg/FallingTree#139]
### Describe the bug

When chopping down a tree, the leaf blocks fall instead of saplings and twigs.

### Minecraft version

1.17

### Fabric API version

0.36.0

### Mod version

2.12

**Comment by Rakambda** [comment]
Is that with a vanilla tree? If so I can't reproduce.

If it's with a modded tree please include its name and mod.

**Comment by Roll4Ignition** [comment]
Okay thank you. It may be something server side then. It is just vanilla
trees. Sorry about that.

**Comment by alphaniner** [comment]
@Roll4Ignition do you have [MineGate · MoreBlocks](https://www.curseforge.com/minecraft/mc-mods/minegate-moreblocks) installed? That mod causes this behaviour.

**Comment by Roll4Ignition** [comment]
I do not. It's only happening on a server I have, no where else
