### ISSUE TITLE
server-sided not working

### ISSUE THREAD

**Issue by Julyoso** [RakambdaOrg/FallingTree#141]
### Describe the bug

Is this working on Multiplayer server? because this works for me on single but not multiplayer. Ive already got it on my minecraft mod file and in the fabric server mod file BOTH OF THEM. (i am using my own server btw).  Please help!

### Minecraft version

1.17

### Fabric API version

1.17 0.36

### Mod version

1.17

**Comment by Rakambda** [comment]
It is supposed to.

Mod version is invalid though.

**Comment by Julyoso** [comment]
wdym version is invalid?

**Comment by Rakambda** [comment]
The mod version `1.17` does not exists

**Comment by Julyoso** [comment]
> The mod version `1.17` does not exists

1.17 of your fallingtrees ?!

**Comment by Rakambda** [comment]
Yeah, it should be something like `1.17-x.y.z`

**Comment by Julyoso** [comment]
But 1.17 works on single player? So does it mean its somewehat compatible for the singleplayer but wont work in the current 1.17 fabric?

**Comment by Rakambda** [comment]
It should work on both. But If I don't know the version I can't test it.

**Comment by Julyoso** [comment]
Ohhh, now i know what you mean by 1.17-x.y.z then its your latest which is 1.17-2.12.0

**Comment by Rakambda** [comment]
I cannot reproduce, works fine for me. My guess is that the mod isn't installed on your server.

If you could provide the `latest.log` from the server logs that'd help.
