### ISSUE TITLE
Whitelist Not Working

### ISSUE THREAD

**Issue by BoltGoesPro** [RakambdaOrg/FallingTree#15]
**Describe the bug**
So i don't know if it's a bug as there is no example on adding to the whitelist, but when i add to the whitelist it looks like this [mekanismtools:wood_paxel] and gives an error for any of those tools

**To Reproduce**
1. add the tools to the whitelist
2. 

**Infos:**
 - Minecraft verson: 1.16.1 forge
 - 1.16.1 Mekanism Tools .430

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

**Comment by Rakambda** [comment]
Hey,

This simply follows the yml file format.

In that case I think you just miss quotes: ["id:name"]. If you need several just add a comma between them: ["id:name1","id:name2"].
