### ISSUE TITLE
Mod don't load

### ISSUE THREAD

**Issue by General-Radek** [RakambdaOrg/FallingTree#174]
### Describe the bug

On launch minecraft forge says this mod is for fabtic however there is forge support added in the changelog for the version...

### Minecraft version

1.17.1

### Forge version

37.0.15

### Mod version

2.12.2

**Comment by Rakambda** [comment]
Can you try redownloading it?
I saw that and actually deleted the pushed version on curse and reuploaded it.

**Comment by General-Radek** [comment]
Done, same problem, nothing changed

**Comment by Rakambda** [comment]
Should be good now, will reappear on curse in a bit

**Comment by General-Radek** [comment]
Downloaded the last file, now it works, and works just fine! Thank you!
