### ISSUE TITLE
(Mod version 2.12.2) Custom tree structures added by datapacks do not break leaves

### ISSUE THREAD

**Issue by NoMoreStars** [RakambdaOrg/FallingTree#185]
### Describe the bug

Attempted to use the FallingTree mod on a world using William Wyther's Overhauled Overworld and Terralith. Expected behavior was that custom tree structures added by both datapacks (for example, trees that generate in Terralith's Siberian Taiga biome) should break just like normal trees, as well as their leaves decaying. Instead, the trees can be chopped like normal but the leaves will not decay.

Here's an example of the type of trees that I'm having trouble with to give you an idea:
![2021-08-07_14 20 05](https://user-images.githubusercontent.com/38673759/128611705-18fac5b1-bc71-4bb2-b66a-8a0ee4d84cf8.png)

### Minecraft version

1.17.1

### Fabric API version

0.37.1

### Mod version

2.12.2

### Relevant log output

```shell
N/A
```

**Comment by Rakambda** [comment]
I don't know how these leaves are declared. But since it is in a datapack I guess it can't extend the LeavesBlock class.
So you probably have to whitelist them.

Edit: maybe it's normal leaves but just with a different color?
In any case the logic for the leaves is always the same: if the block is considered as leaves, the mod simply accelerate the random ticking speed on. So as long as the leaves are connected to the tree, they should decay.

**Comment by Rakambda** [comment]
Tried with a lot of those trees and didn't have any issue. Didn't find the ones you showed on the screens are there's a ton of biomes...

**Comment by NoMoreStars** [comment]
Try the seed -2076151314 and run the command /locatebiome terralith:siberian_taiga and teleport to the coordinates that are listed in chat.

**Comment by Rakambda** [comment]
![2021-08-07_22 46 34](https://user-images.githubusercontent.com/1688389/128613468-e1dd1388-2bb8-429d-81e1-eccfdeb6e055.png)
Doesn't really get me to the same place.

Edit: Ok, found some trees that don't have leaves decaying

**Comment by Rakambda** [comment]
The reason is because the leaves generated are marked as persistent so they won't decay. It's the same as if they'd have been placed by the player.

![image](https://user-images.githubusercontent.com/1688389/128613566-7905cdf3-1191-43fe-87ae-568954f22932.png)

**Comment by NoMoreStars** [comment]
Ah, gotcha. I'll make sure to report that the the dev of the datapack. Thanks!
