### ISSUE TITLE
Breaking Leaves option causes leaf blocks to tick wildly.

### ISSUE THREAD

**Issue by Snaitf** [RakambdaOrg/FallingTree#20]
**Describe the bug**
I've noticed, that in 1.15.2, if break_leaves is set to true, whenever you manually break a leaf block, it causes any other leaf blocks touching it to tick over and over.  While, this behavior isn't noticeable in vanilla, it can break other mods.  Nature's Aura, or Fruit Trees, for example, where waiting for leaf blocks to tick for something to happen, is extremely accelerated by your mod.

**Detailed Examples:**
In Nature's Aura, you need to turn a leaf block golden, and wait for a while, so it can slowly spread to surrounding leaf blocks, eventually converting all the leaves that are touching.  However, if you break a leaf block manually, it causes the surrounding ones to immediately convert, making it extremely easy to get the golden leaves.

In Fruit Trees, leaf blocks produce fruit inside them over time and eventually drop it as an item, but if you break a leaf block, the surrounding ones will immediately start producing and dropping fruit at an alarming rate, over and over.

**Conclusion:**
Setting break_leaves to false, stops this behavior.  So, I'm currently forced to use this mod for only the tree chopping, and a separate mod for the leaves (fast leaf decay) which doesn't cause this to happen.

**To Reproduce**
1. Enable leaf breaking from this mod.
2. Install another mod that relies on leaf blocks changing over time.
3. Manually break a leaf block touching another leaf block where ticking is visible.

**Comment by Rakambda** [comment]
I'm not too familiar with this mod so not too too sure what would be the best end result. Though your explanation was quite clear, so thanks for that.

I tried to reduce as much as I could the random ticks being generated on the leaves.
Can you try [this version](https://github.com/RakSrinaNa/FallingTree/files/5170456/FallingTree-1.15.2-2.2.1b.zip) (mod is inside the zip file) and tell me if this is better and maybe comparable to what FastLeafDecay does?
(In my testing there's still some golden leaves items popping out of the leaves sometimes, but the spreading seems to have been reduced a bit)

**Comment by Snaitf** [comment]
That seemed to do the trick!

From what I can tell, both Nature's Aura and Fruit Trees are behaving the way they should now.

Good work, and so fast, too  :)

**Comment by Rakambda** [comment]
I'll officially publish the change on Curse tomorrow I guess 😉
