### ISSUE TITLE
Config / Documentation - Explain how to make lists

### ISSUE THREAD

**Issue by ITCMD** [RakambdaOrg/FallingTree#208]
### Describe the feature

Example:
```
	#List of tools that should not be considered as tools.
	#INFO: This wins over the whitelist.
	blacklisted = []
```
This does not say how to separate items in a list. I would assume commas and spaces, however documentation in the config and / or the wiki would be greatly appreciated.

**Comment by Rakambda** [comment]
The thing is that forge and fabric uses different format and will be hard to detail that without making it more complicated than it is.

Fabric follows a JSON5 format, while forge follow it's standard config format (toml I think).

What I can do though, is provide an example config as an example with all fields filled.

**Comment by ITCMD** [comment]
Ok, just for the sake of me being able to config this for my server today, how does toml make lists? It's not a language I've worked with before.

**Comment by Rakambda** [comment]
I can't check right now if it is TOML or not, but if it has a .toml extension then it should be.
In that case the black/whitelists will have same format as JSON: `["modid1:block1","modid2:block2"]`.

(https://github.com/toml-lang/toml#example)

**Comment by Rakambda** [comment]
Added examples that doesn't make sense but that are fully filled.

https://github.com/RakSrinaNa/FallingTree/wiki/Settings---Examples
