### ISSUE TITLE
Crash on fabric 1.16.2

### ISSUE THREAD

**Issue by Zano1999** [RakambdaOrg/FallingTree#22]
It crash with the following error:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'falling_tree'!
Exit Code: -1

**Comment by Rakambda** [comment]
Can you provide your `debug.log` file (in the logs folder) after having the crash?

**Comment by Zano1999** [comment]
https://pastebin.com/y5ZbC5qa

**Comment by Rakambda** [comment]
Seems like there's quite a big part of the log file missing there.

Though, that second line (`Conflicting versions found for fabric-api-base: used 0.1.3+12a8474cfa, also found 0.1.3+12a8474c4e`) is weird. Seems like you have the fabric-api mod twice.

Anyway, from what I see there the fabric-api isn't the latest, try with it ;) 
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3049174

**Comment by Zano1999** [comment]
Thanks, now it work ;)
