### ISSUE TITLE
Invalid block/tool ids treated as air

### ISSUE THREAD

**Issue by WenXin20** [RakambdaOrg/FallingTree#221]
### Describe the bug

Any invalid block or tool ids are treated as air. I discovered this while remaking my modpack, a mod was not installed, so the `simplytea:tea_trunk` was treated as air. This meant that whenever I tried to chop down an oak tree, it would give me the error of too many blocks to cut down. The limit is currently at 2000 blocks, with `mixed_logs` set to true.
For tools, I had Gobber2's paxels whitelisted, but did not have the mod installed, so I was able to chop down a tree with an empty hand (once the invalid log ids were removed).

### Minecraft version

1.16.5

### Forge version

36.2.4

### Mod version

2.11.5

**Comment by Rakambda** [comment]
As this can be prevented by having a valid config and so isn't blocking, I'll push the fix only in the latest version.
