### ISSUE TITLE
Ability to config limit

### ISSUE THREAD

**Issue by Lobituki** [RakambdaOrg/FallingTree#228]
### Describe the feature

Could you add the ability to configurate the limit of blocks able to be broken to all hells
please
this modpack has forests that have connecting trees and because of either my STUPID self or the inability to config the limit I CANNOT INSTACUT TREES. 😔

**Comment by Rakambda** [comment]
> to all hells

What do you mean?

And the limits can already be configured. See [the wiki](https://github.com/RakSrinaNa/FallingTree/wiki/Settings) (trees > Max scan size & trees > Max (break) size).

**Comment by Lobituki** [comment]
oh lmao ok ty
i mean i couldn't click on the config, it was all greyed out
ohhhh ok nvm ty
