### ISSUE TITLE
Long tree breaking animation not working

### ISSUE THREAD

**Issue by daeeros** [RakambdaOrg/FallingTree#239]
### Describe the bug

When I break a tree on the server, the block that I hammer breaks every time as usual and appears occupied, and so on until I cut down the whole tree, although the players on the other hand show a long animation of breaking without disappearing, how can I also do what I would have long animation of breaking and not breaking every second? I tried to install the mod both on the client and on the server, but nothing helped.

### Minecraft version

1.16.5

### Fabric API version

0.40.6

### Mod version

2.11.5

**Comment by Rakambda** [comment]
I'm not sure to understand the whole thing.

> I hammer breaks every time as usual and appears occupied, and so on until I cut down the whole tree

Seems like you use the SHIFT_DOWN breaking mode ?

**Comment by daeeros** [comment]
> I'm not sure to understand the whole thing.
> 
> > I hammer breaks every time as usual and appears occupied, and so on until I cut down the whole tree
> 
> Seems like you use the SHIFT_DOWN breaking mode ?

No, it is off, the felling of the tree is carried out for a long time and completely and not one block at a time, I will try to record a GIF and attach it here

**Comment by daeeros** [comment]
As we can see one block breaks a bunch of times, I just would like the block that I cut to break in time as much as it takes to cut a tree. It happens for other players from the outside, but for me it breaks down and appears again.

[https://www.youtube.com/watch?v=vkJdxtTqms8](url)

**Comment by Rakambda** [comment]
The value of "Settings > Tools > Speed multiplicand" is probably different on the client and on the server. If they are not the same you'll see the desynchronization you have.
