### ISSUE TITLE
Config for turning off chat informations about cutting tree

### ISSUE THREAD

**Issue by I3estOFF** [RakambdaOrg/FallingTree#246]
### Describe the feature

![image](https://user-images.githubusercontent.com/63112899/144143643-bb04af1f-3647-43f9-85ff-724803c4d466.png)

**Comment by Rakambda** [comment]
Why not, I can set it as a new notification mode. The issue with doing that is that people may not understand why a tree isn't cut sometimes. At least like this it indicates you to shift/unshift to disable the mod on breaking. But well, it wouldn't be set as default so people should be aware of the consequences.
I'll try to release it by the end of the week.


In the meantime you can probably set the notification mode to ACTION_BAR and you should be a bit less spammed I think.
https://github.com/RakSrinaNa/FallingTree/wiki/Settings---General

**Comment by I3estOFF** [comment]
I understand that some people won't know why tree isn't cut, but this option should be in config for others ;D because if tree is too big to cut, you have to cut it by yourself with axe, but when you do that, every time you break the log you have this information. So when tree is to big you have three options: leave it alone and find another tree, cut it with hand or cut it with axe with spam on chat :'D

For now i turned of chat, but chat is important when you're playing on server or making modpack, so this config should be great :))

**Comment by Rakambda** [comment]
You have a 4th option: sneak or unseak deping on the "[reserve sneaking](https://github.com/RakSrinaNa/FallingTree/wiki/Settings---General)" value. But yeah, won't hurt to have it as an option.

Out of curiosity, what MC version are you using? I still don't know if I add this only to 1.18 or also backport it to 1.17.

The "issue" it'll bring and that people have to be aware is that **every** "notification" will be silenced (this includes, "tree too big", "search aborpted", "prevented tool break").

**Comment by I3estOFF** [comment]
I mostly use it on 1.16.5 and 1.17
Btw i love your mod! The best of all about cutting tree, other haven't that much configs, it is very helpful in making modpacks!

**Comment by Rakambda** [comment]
You can try that version to see if it matches your needs. I didn't test it myself 😆 
You should have a new option "NONE" in the notification mode.

https://www.dropbox.com/t/s0TEZ1zy5XpYy0CD

**Comment by I3estOFF** [comment]
can u make it for 1.16.5 also? Now i'm making modpack on this version

**Comment by Rakambda** [comment]
1.16.5 hasn't been updated for nearly half a year and is missing all the changes since then, so I won't be making a new version of it.
I usually maintain only the current version, and the previous one for a bit after a change (like now I'll do 1.17 & 1.18).

**Comment by I3estOFF** [comment]
Oh okay.. Can you tell me how to make it or i need to search for other mod like this? :/

**Comment by Rakambda** [comment]
I could do a version and post it here where there's no messages (hard-coded, won't be an option), but wo t release it and will have less features than the 1.17 version

Another thing but i don't know if it's possible: the mod uses language files, so it may be possible to override them with a resource pack? And set it to a blank value so "blank" is spammed instead.
Not perfect but can be an external solution.

**Comment by I3estOFF** [comment]
Alright, if you can send it to me i'll be happy :) I want to use it just for my modpack

**Comment by Rakambda** [comment]
[FallingTree-1.16.5-2.11.5.zip](https://github.com/RakSrinaNa/FallingTree/files/7643791/FallingTree-1.16.5-2.11.5.zip)

**Comment by I3estOFF** [comment]
I'm looking for Notification mode in config, but can't find it.
Where i should write it?

**Comment by Rakambda** [comment]
For 1.16 it's forced, nothing to change.
For the released 1.17 it's in "general > notification mode".

https://github.com/RakSrinaNa/FallingTree/wiki/Settings---General I have to edit the wiki with the new "NONE" value.

**Comment by I3estOFF** [comment]
Oh alright! thanks :)
