### ISSUE TITLE
2.15.1 fabric shift_down doesn't work

### ISSUE THREAD

**Issue by ghost** [RakambdaOrg/FallingTree#258]
### Describe the bug

Instantaneous still works but shift_down seems broken in the latest version, chopping just removes the block as in vanilla - higher blocks do not move down. Reverting to 2.15.0 fixes this, nothing in logs.

### Minecraft version

1.18

### Fabric API version

0.44.0

### Mod version

2.15.1

**Comment by Rakambda** [comment]
That's weird, I didn't change anything on that 😕 What seems to happen is that it breaks the furthest log like it should AND the block you hit.

Does it seem better with this version? https://www.dropbox.com/t/5eOG5DHgAIjnHWyR

**Comment by ghost** [comment]
Yeah, back to the normal shift_down behaviour with that version.
