### ISSUE TITLE
Notifications dont have any text

### ISSUE THREAD

**Issue by KlutzyBubbles** [RakambdaOrg/FallingTree#260]
### Describe the bug

For example 'chat.fallingtree.tree_too_big'. when i chop down a tree that is too big, the message just contains 'chat.fallingtree.tree_too_big' instead of an actual message. I dont know if this means the client side mod is required but i wasnt able to find any config to change that message either.

I am using this mod as a server sided mod for vanilla clients, so installing it on the client side isnt an option.

### Minecraft version

1.18

### Fabric API version

???

### Mod version

2.15.2

**Comment by Rakambda** [comment]
How minecraft works is that it sends this value to the client, and then they display the correct value based on the language used.

I think you only need to provide these values to the client, the full mod isn't needed.

I haven't tested it, but I guess you can package them inside a standard resource pack and deliver it to your clients as the server resource pack and make it mandatory.
I'm not really knowledgeable on resource packs so you'll have to document yourself a bit about it, but there should be plenty of guides online.
The Lang files that the mod provides are in common/src/main/resources/assets/fallingtree/lang

**Comment by Rakambda** [comment]
Version 3.0.0 will also be required on clients, so this is getting irrelevant. If staying on previous versions I guess this resource pack is the way to go.
