### ISSUE TITLE
Speed Multiplicand feature bug

### ISSUE THREAD

**Issue by chrisgates301** [RakambdaOrg/FallingTree#267]
### Describe the bug

When i first installed the mod it worked correctly, i set it to 1 so it would take the time of chopping every log, but after a restart it stoped working, i havent added any other mod than the ones i already use.

### Minecraft version

1.16.5

### Forge version

Latest

### Mod version

Latest

**Comment by Rakambda** [comment]
I cannot reproduce it.
Also please fill up the values properly, `latest` isn't really the latest as it is only available for 1.18+.

Is it single player or multiplayer?

Does this also happen if you have **only** FallingTree?

If yes can you provide steps to reproduce? "restart" for example is a bit vague to me. Do you restart the world, the game, ... ?
Like:

* Set speed multiplicand to 1
* Chop a tree => speed multiplicand is applied
* Restart Minecraft
* Chop a tree => speed multiplicand is ignored
