### ISSUE TITLE
Cant get the mod to work on server

### ISSUE THREAD

**Issue by Dynis91** [RakambdaOrg/FallingTree#285]
### Describe the bug

Hi, Have tried both 1.18.1-3.1.0b2 and 1.18.1-3.0.1 for forge but cant get it to work, leaves fall instantly but the tree wont go down :/

### Minecraft version

1.8.1

### Forge version

39,0,9

### Mod version

both 1.18.1-3.1.0b2 and 1.18.1-3.0.1

**Comment by R3tr0PAG** [comment]
I'm having the same issue but with Fabric.

**Comment by R3tr0PAG** [comment]
Ok so i had to double/tripple check but i having the same problem on my server. Only that i'm on fabric

First i thought it just was a bug then i noticed that in version 3.0.0 added an enchantmend "Chopper", i turned that option to false in server config but still it would only break the leaves.

Minecraft V: 1.18.1
Fabric V: 0.12.12
Mod Version: 3.0.1

**Comment by Rakambda** [comment]
Can you share your config file?

**Comment by Dynis91** [comment]
```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "instantlyBreakWarts": false,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "requireEnchant": true,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0
  },
  "reverseSneaking": false,
  "breakInCreative": false,
  "notificationMode": "ACTION_BAR"
}
```

**Comment by Dynis91** [comment]
theres mine on the forge server :)

**Comment by Rakambda** [comment]
In your case the enchant is activated, we're ok on the fact that it doesn't break the tree with an enchanted axe ?

**Comment by Dynis91** [comment]
aah okey ^^ nah i want it to break with enchants so will fix it :D thanks <3

**Comment by Rakambda** [comment]
I tried with version `1.18.1-3.1.0b2` on both fabric & forge and works for me.
So my guess is that the enchant wasn't applied.

For @R3tr0PAG I tried it with the same config and just changed `requireEnchant` to `false`. It does chop trees with/without the enchant. There must be some other condition that isn't met. Leaves at the top missing or something like that ?

**Comment by frenchiveruti** [comment]
I assume it would be wise to set the enchantment to false by default, and also make it big bold red letters that there's an **enchantment** in the mod, on the curseforge page where people usually download the mod.  
Suggestion:
![imagen](https://user-images.githubusercontent.com/1095997/149783138-a2e96788-d9ff-4e6f-9b71-dfce4139b6cd.png)

I also thought it didn't work (of course I added 2+2 and the "mod was loaded" is enough giveaway that the mod 'works' but there's something missing), but simply checked the config file.

**Comment by Rakambda** [comment]
#291, already released as beta. Doesn't make much sense to make it bold red anymore as it'll become the default now. If enchant is activated then users would have activated it and therefore would be aware of it.

Indeed, assuming that users read the changelog wasn't the wisest idea and lead to confusions.

**Comment by frenchiveruti** [comment]
Haha true.

**Comment by Seva41** [comment]
Hi, i second @R3tr0PAG. I'm on Fabric 0.12.12, FallingTree 3.2.0b1 and MC 1.18.1.
The mod works fine on singleplayer worlds but i can't get it to work on my server. I copied already the json config file to the server from the client. Also tried adding manually some axes to the allowed list but doesn't help.

```
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "instantlyBreakWarts": false,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [
      "minecraft:diamond_axe",
      "minecraft:iron_axe",
      "minecraft:netherite_axe"
    ],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "requireEnchant": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0
  },
  "player": {
    "allowedTags": []
  },
  "reverseSneaking": false,
  "breakInCreative": true,
  "registerEnchant": false,
  "notificationMode": "ACTION_BAR"
}
```

**Comment by Rakambda** [comment]
Hmm, tried with your provided config and it does work on a forge server with a client with/without the mod 🤔 

Maybe I have some changes that I didn't publish in the b1? What if you try with the dev version I used?
[FallingTree-1.18.1-0.0.1-dev.zip](https://github.com/RakSrinaNa/FallingTree/files/7900216/FallingTree-1.18.1-0.0.1-dev.zip)

**Comment by Seva41** [comment]
Just tried, doesn't work. At this point i'm not sure if i'm doing things right. I copied the .jar in the mods folder for both my client and the server, copied the new config file to the configs folder on the server and restarted both client and server.

**Comment by Rakambda** [comment]
At the start of the server you should see `[20:59:53] [main/INFO]: Found mod file FallingTree-1.18.1-0.0.1-dev.jar of type MOD with locator {mods folder locator at E:\Minecraft\test-forge\mods}` indicating the mod has been found.
If that is the case then the loaded config is probably not the one mentioned above.

**Comment by Rakambda** [comment]
https://youtu.be/HtT0InTpdvs

**Comment by Seva41** [comment]
I'm using Fabric tho, and doesn't look like that. However, the mod appears in the list of loaded mods at the start of my server, so i guess it's loaded correctly. Maybe some compatibility issue?

I have Appleskin, Cloth Api, Cloth Config, Dynview, Fabric Api, Fallingtree, Lithium, Phosphor and Sodium.

**Comment by Rakambda** [comment]
You can try with that version, logs should tell in a bit more details what's happening.
[FallingTree-1.18.1-0.0.1-dev.zip](https://github.com/RakSrinaNa/FallingTree/files/7916619/FallingTree-1.18.1-0.0.1-dev.zip)
