### ISSUE TITLE
Mod not working for me 

### ISSUE THREAD

**Issue by Ramon247** [RakambdaOrg/FallingTree#286]
### Describe the bug

I am new into getting mods. I have the mod in the mod folder but when I go into the world I use a wooden axe and it says "first position set to(xx,xx,xx)" and it doesn't even break the wood. If I use a stone then it breaks just the one it doesn't do what the mod is supposed to do. Help!  Tried both 1.18.1-3.0.1 and 1.18.1-3.1.0b2

### Minecraft version

1.18.1

### Forge version

39.0.9

### Mod version

1.18.1-3.1.0b2

**Comment by Rakambda** [comment]
The wooden axe is probably used for worldedit.
For the stone one, starting version 3 of Fallingtree you need to put the Chopper enchantment on it. If you want to not use the enchant you can change this behavior in the config.
