### ISSUE TITLE
Honor enchantments for leaves

### ISSUE THREAD

**Issue by Syhlo** [RakambdaOrg/FallingTree#292]
### Describe the feature

I've been using a datapack on my server for a while now called Timber. I'm looking to switch to this mod soon since I want to gate the ability to insta-mine trees behind an enchant and this fits that perfectly.

But one of the things I really like about Timber is that it takes into consideration the enchantments on the axe while breaking the leaves. For example, if your axe has silk touch then the leaves will be silk touched or if it has fortune you'll get additional drops, etc.

Any interest in adding this eventually?

**Comment by Rakambda** [comment]
As it is right now leaves are not broken by the player, simply they decay faster.

However it should be doale to add an option that breaks the leaves. That means that enchants are applied, but the counter part is that your tool looses more durability (as you don't just cut the log).

The question is more "how" ? Like adding a global config can be a bit... annoying to change (and on a server, you don't really decide as a player 😆 ). I guess that people don't want to always chop down the leaves and lose more durability. It's more something that "happens for a little white", basically when you want to gather leaves.
But I don't have much more ideas than a config. As the mod can also be only server sided I can't add key configurations that could act as a toggle.

**Comment by frenchiveruti** [comment]
I want to say, please leave the mod as is, it's simple, it works, and already allows customization.   
If you start extending you ruin the simplicity that already makes it great.  

Thanks,

**Comment by Rakambda** [comment]
I get your point of view. However this still can be considered.
FallingTree is far from being simple, there's a lot of configurations that makes it quite complex.

Though keeping it as a "simple mod that just works" by default is something I keep in mind. If you don't put your head in the config you'll just have it the simplest way. However if you're a bit more into customization then options are still available to you.
The 3.0.0 release kinda hurt that "keep it simple" stuff as the enchant was introduced and enabled by default. Probably should have been disabled by default as it lead to lots of confusions.

Regarding the issue itself, to me it doesn't sound like a bad idea. Just wondering how to add it in a simple way, and as opt-in.
I just thought of this writing this response, but @Syhlo maybe you can try adding the leaves in the "allowed leaves (needs breaking)" config. I haven't tested but this may actually do what you're looking for.

**Comment by Syhlo** [comment]
I went ahead and tested it just now -- seems to be working. Thanks! :)
