### ISSUE TITLE
preserve tools not working when "damageMultiplicand" > 1.0

### ISSUE THREAD

**Issue by scarf005** [RakambdaOrg/FallingTree#299]
### Describe the bug

```
[Preserve tools] This controls how the mod behaves when a tree is cut with a tool that is going to break.
No: The tool will be fully used and broken.
Yes: The tool won’t be fully used and be left with 1 of durability.
```
however tools with durability 1 would
- not break any blocks
- refuse to get broken
- with message from `"chat.fallingtree.prevented_break_tool"`.

regardless of how the configuration above is set.

### Minecraft version

1.18.1

### Fabric API version

0.46.1

### Mod version

3.2.0b1

### Relevant log output

```java
Your tool is about to break, go repair it or get a new one.
```

**Comment by Rakambda** [comment]
I'm not really getting what's the issue here.

When you have 1 of durability the tool breaks and you expect it not to break?

**Comment by scarf005** [comment]
the exact opposite. i was expecting the tool to break when its durability is 1, but it doesn't. i cannot destroy my tool, the mod would just send `"chat.fallingtree.prevented_break_tool"` and refuse to break the tool. despite `preserve tool` config set to `no`.

**Comment by Rakambda** [comment]
I cannot reproduce.

https://user-images.githubusercontent.com/1688389/150840773-883e5f49-d70a-4b63-a100-3de68b9af624.mp4

* If you play with other mods, can you reproduce the behavior with FallingTree alone?
* Do you plan on server ? If so this is the server config that is taken into account.
* Can you share your `fallingtree.json` content?

**Comment by scarf005** [comment]
to reproduce the issue, change `"damageMultiplicand"` to any value bigger than `1.0`. for example
- issue happens on: `1.2`, `1.5`, `2.0`.
- issue does not happen on `1.0`, `0.7`, `0.5`

here's the configuration: [fallingtree.json.txt](https://github.com/RakSrinaNa/FallingTree/files/7930958/fallingtree.json.txt)

**Comment by Rakambda** [comment]
I don't have the time to test it right now, but I made changes where I think the issue is. If you wanna test it before you can grab the modified version [here ](https://github.com/RakSrinaNa/FallingTree/actions/runs/1744132709) (artifacts at the bottom).

**Comment by Rakambda** [comment]
[This one](https://github.com/RakSrinaNa/FallingTree/actions/runs/1744183068) should behave a bit better I think.
The one mentioned above was probably breaking several blocks even though only one should have been broken.
