### ISSUE TITLE
1.15.1 Break Leaves destroys leaves on new trees

### ISSUE THREAD

**Issue by Yamza** [RakambdaOrg/FallingTree#3]
**Describe the bug**
While having break_leaves set to true, any sapling planted will have their leaves break when grown.
```
#When set to true, leaves will be broken instantly
break_leaves = true
```
https://i.imgur.com/87fzlSh.gifv

**To Reproduce**
1.  Plant a sapling
2. Wait for it to grow

**Infos:**
 - Minecraft verson: 1.15.1
 - Mod version: FallingTree-1.15.1-2.0.1+11
 - Forge 30.0.35

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

**Comment by Rakambda** [comment]
You can try 2.0.2, should fix the issue.
