### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by sav-11** [RakambdaOrg/FallingTree#30]
**Describe the bug**
it doesnt work when i loaded it up on fabric 1.16.2 and i tried to redownload it but it still doesnt work
**To Reproduce**
1.  fix it
2. help me 

**Infos:**
 - Minecraft verson: [e.g. 1.16.2]
 - Mod version: [e.g. 1.0.0]?????

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

**Comment by Rakambda** [comment]
Your explanation is quite vague.
At least provide your `debug.log` file.

To me it sounds like an issue with your setup. Are you even able to load any other mods?
