### ISSUE TITLE
Items stop allowing stacking after drop.

### ISSUE THREAD

**Issue by ezrielSG** [RakambdaOrg/FallingTree#304]
### Describe the bug

Some items when dropped now are unstackable in inventory. I couldn't find any log data on this, only that it seems to have also been a recurring issue with the "Timber" mod some months back.

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/3062259-items-not-stacking

It seems that removing the mod from the mods folder and reinserting it fixes the issue.

### Minecraft version

1.18.1

### Fabric API version

0.46.3

### Mod version

1-3.1.0

**Comment by Rakambda** [comment]
Honestly I don't really know what to say to this x) 
The NBT data is probably different and so they don't stack. But I don't really manage the drops part myself. I just [ask Minecraft to do it](https://github.com/RakSrinaNa/FallingTree/blob/1.18.1/fabric/src/main/java/fr/raksrinana/fallingtree/fabric/common/wrapper/BlockStateWrapper.java#L55).
With all the testing I did I never encountered that issue and without ways to reproduce it (other than randomly) I can't really investigate much.

**Comment by Rakambda** [comment]
If you can reproduce it "reliably" (like it happens every so often and no too rarely), is it with vanilla logs + vanilla axe or is there another mod involved?
