### ISSUE TITLE
"requireEnchant" missing from version 3.2.0

### ISSUE THREAD

**Issue by Zhyn-exe** [RakambdaOrg/FallingTree#308]
### Describe the bug

3.2.0b2 and 3.2.0 are missing the require enchant option in the mod menu, resulting in not being able to enchant anything with Chopper (with a book and anvil, or an enchanting table).
I tried manually adding ""requireEnchant": true"" under the tools section but that didn't seem to work either.

3.2.0b1 seems to still have the option and works.

Edit*** registerEnchant was set to true, allowing me to creative in the book, but unable to apply it.

### Minecraft version

1.81.1

### Fabric API version

0.46.4

### Mod version

3.2.0

**Comment by Rakambda** [comment]
This has moved to `enchant.registerEnchant`. I agree this is not that obvious and wiki doesn't give exact keys.

I'll try making it clearer in the changelog.

**Comment by Zhyn-exe** [comment]
Sorry, I'm not following. Is "enchant.registerEnchant" something I need to add to the config?
All that's in the new config is:
  "enchantment": {
    "registerEnchant": true,
    "hideEnchant": false

Also maybe unrelated, the tooltip in modmenu for "registerEnchant" is broken.

**Comment by Rakambda** [comment]
You're right my bad, I was replying from what I remembered. The JSON you put is what you can modify with 3.2.0. If you register the enchant then it'll be required on the tools.

I'll look why the modmenu doesn't display the tooltip properly. You can find it [here](https://github.com/RakSrinaNa/FallingTree/blob/1.18.1/common/src/main/resources/assets/fallingtree/lang/en_us.json#L202-L209) for now.

**Comment by Zhyn-exe** [comment]
I think I see where the confusion is. ""registerEnchant": true" is not working like it used to. After testing standalone I realized it is working on the default enchanting table.

But you can no longer enchant Chopper to a book. You can still find the enchanted Chopper book with RoughlyEnoughItems, but it still wont let you combine it in an anvil with an axe.

Compatibility with Enchanting Infuser is also broken now, the enchant doesnt show up. (Mod lets you pick which enchantments you can use). https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-fabric

**Comment by Rakambda** [comment]
This isn't linked to the `registerEnchant`. I made changes to only enchant valid tools (#290). I didn't think of the book and will have to add it.

For Enchanting Infuser I'll have to look into it, seems weird it isn't showing the enchant for axes (the tools you try to enchant is maybe not recognized as an axe and not whitelisted?).

**Comment by Rakambda** [comment]
Looked a bit into it and it seems weird. The book part is part of vanilla Minecraft. Every enchant is automatically applicable to a book. As for the tool, it'll end up in my part of the code deciding if the tool is an axe or not.

> But you can no longer enchant Chopper to a book.

Will have to try a bit more with vanilla table but seems like it's possible.
![image](https://user-images.githubusercontent.com/1688389/152841770-1d8317f8-e777-45e1-a938-5fc20b5193c1.png)

> but it still wont let you combine it in an anvil with an axe

Same deal as with the enchant table, need a tool that is considered an axe by the mod.
![image](https://user-images.githubusercontent.com/1688389/152843439-0d188e4f-fab9-446b-8398-726b2c3a4785.png)

> Compatibility with Enchanting Infuser is also broken now

I manage to see the Chopper enchant in the mod you mentioned:
![image](https://user-images.githubusercontent.com/1688389/152841647-7c355082-e7cd-4cae-94d7-506bdf096faa.png)

---

For the book I have no idea why you don't see it. For the tool maybe you use one that isn't considered an axe?

**Comment by Zhyn-exe** [comment]
I tried 64 books in a vanilla enchanting table and it did not appear on a book, but yeah Enchanting Infuser lets you put it on a book.

In survival mode combining the axe with Chopper is crossed out on an anvil, but in creative mode it works.
I'm still unable to see Chopper for any axe in Enchanting Infuser, whether I'm in creative or survival.

I dunno why it's being so weird, I'm testing on a fresh install, with a newly generated FallingTree config, and only changing  "registerEnchant": true.
These are the only mods installed:
	- architectury 3.6.17
	- cloth-config 6.1.48
	- enchantinginfuser 3.1.1
	- fabric 0.46.4+1.18
	- fabricloader 0.12.12
	- fallingtree 3.2.0
	- forgeconfigapiport 3.1.1
	- modmenu 3.0.0
	- puzzleslib 3.1.3
	- roughlyenoughitems 7.2.418

**Comment by Rakambda** [comment]
> In survival mode combining the axe with Chopper is crossed out on an anvil, but in creative mode it works.

Weird, it works for me
![image](https://user-images.githubusercontent.com/1688389/152854710-d501bdf0-5d0f-47ef-9aaf-806927c83d3b.png)

> I tried 64 books in a vanilla enchanting table and it did not appear on a book

Indeed the enchantment table is not really selecting enchants the way I thought it would, and using default Minecraft values seems to make the enchant super unlikely to appear.

I made a change and should make it it now appear for both books & tools more often (mostly in the first slot). You can test it with [this version](https://github.com/RakSrinaNa/FallingTree/actions/runs/1808550736) (artifact at the bottom).
