### ISSUE TITLE
Filesize Issue

### ISSUE THREAD

**Issue by BaccarWozat** [RakambdaOrg/FallingTree#315]
### Describe the bug

The download for Falling Tree for 1.18.2 is only 261 bytes. That can't be right. And in any case it doesn't do anything. It just seems to consist of `manifest.mf`.

### Minecraft version

1.18.2

### Fabric API version

0.47.8

### Mod version

3.3..0

**Comment by Rakambda** [comment]
Indeed. Uploading it to curse first day of 1.18.2 when there was lots of server unavailability was maybe not the best idea 😆 
It is fine on modrinth though. I'll reupload it on curse, thanks for the heads up.
