### ISSUE TITLE
1.18.1 not working forge

### ISSUE THREAD

**Issue by irusV4** [RakambdaOrg/FallingTree#316]
### Describe the bug

hello, I've downloaded this mod for 1.18.1 forge and the only options are 1.18.2 and I've downloaded that one to see if it'll work, and it doesn't even show up in my config menu, I've deleted and redownloaded it multiple times, why isn't it working if its 1.18 and why isn't there a 1.18 or 1.18.1 version.

### Minecraft version

1.18.1

### Forge version

30.1.2

### Mod version

0.0.1

**Comment by Rakambda** [comment]
1.18/1.18.1/1.18.2 are available on curseforge/modrinth. Go into the files tab and you'll see them (https://www.curseforge.com/minecraft/mc-mods/falling-tree/files).

1.18.2 had issues with its upload and I re-uploaded it (#315)

**Comment by irusV4** [comment]
Okay thank you very much
