### ISSUE TITLE
Version 1.18.2 does not work on Forge

### ISSUE THREAD

**Issue by BingYanchi** [RakambdaOrg/FallingTree#319]
### Describe the bug

Version 1.18.2 does not work on Forge

### Minecraft version

1.18.2

### Forge version

40.0.12

### Mod version

3.3.0

**Comment by Rakambda** [comment]
Indeed, 1.18.2 is tagged with only Fabric as it only supports Fabric. At the time I made it Forge was not yet available for 1.18.2.

I'll add support for it.
