### ISSUE TITLE
Speed multiplicand exception

### ISSUE THREAD

**Issue by Dr-WeiAL** [RakambdaOrg/FallingTree#324]
### Describe the bug

Speed multiplicand does not affect the roots of planted trees or naturally occurring trees, while the roots of manually placed trees are affected when you cut them.

### Minecraft version

1.18.1

### Forge version

39.1.2

### Mod version

3.2.1

**Comment by Rakambda** [comment]
What do you mean by "roots"?

**Comment by Dr-WeiAL** [comment]
> What do you mean by "roots"?

This is a machine translation, sorry
I was referring to the bottom piece of wood of the tree

**Comment by Dr-WeiAL** [comment]
![1](https://user-images.githubusercontent.com/47446553/158422918-46f17dc0-ea2f-4ba5-b987-2172198fecaf.gif)
Here the Speed multiplicand is set to 2

**Comment by Dr-WeiAL** [comment]
Well, I only installed FallingTree and there is no problem, and it is time to check which mod is incompatible with

**Comment by Dr-WeiAL** [comment]
Oh I found it, sorry to bother you, it's Reap reason
