### ISSUE TITLE
Stripped wood

### ISSUE THREAD

**Issue by PortableGames** [RakambdaOrg/FallingTree#325]
### Describe the bug

It doesn't work on trees that have a trunk from Stripped Wood 

Used for example in the Terralith datapack

### Minecraft version

1.18.2

### Fabric API version

Latest

### Mod version

Latest

**Comment by Rakambda** [comment]
Stripped logs are intentionally not whitelisted by default as in vanilla it's more likely to the used in builds (#196).

If you want them counted as logs you'll have to add them manually in the config.

**Comment by Rakambda** [comment]
You may be able to add the logs tag itself to your config to add them all at once (`#minecraft:logs` in the allowed logs).
