### ISSUE TITLE
Can't use Chopper book in anvil when in survival

### ISSUE THREAD

**Issue by Laifsyn** [RakambdaOrg/FallingTree#331]
### Describe the bug

So even though I can see the enchant, I can't enchant it onto axes. I can enchant it to other books though. Is it by chance using a tag like c:tools/axes or something? idk what else to provide so to make it easier to fix

### Minecraft version

1.18.1

### Fabric API version

0.13.3

### Mod version

FallingTree-1.18.1-3.2.1

**Comment by Rakambda** [comment]
It should appear on tools that are considered as an axe by the mod. This means axes and white listed tools.

What do you mean by "can't enchant it"?

- you see the enchant in the enchant table for axes but can't get it from the table?
- you only see it in the enchant table for books but not the rest? (In that case does getting the book and applying it on the axe works?)
- you don't see it in the enchant table at all and you get books another way?



Edit: I just read the title and this is in the anvil. So if I get it right you have a book with the enchant on it but can't apply it to the axe. However you can merge books.

Onto what axe do you try to apply the book?

**Comment by Laifsyn** [comment]
Vanilla axes. Preferably to also include modded axes.
iirc the tag I see in REI was something like "fabric:axes" or "fabric:tools/axes"

**Comment by Rakambda** [comment]
By default axes are not detected through a tag (as it isn't vanilla), it's purely based on Minecraft code (what makes the axe item). So the vanilla ones should work.

For the modded ones, either the author did it in a way that will be supported by FT, otherwise you'll have to whitelist them.

I managed to reproduce the issue. Seems like it works in creative but not survival.

**Comment by Rakambda** [comment]
[Here](https://github.com/RakSrinaNa/FallingTree/actions/runs/2104441787) you'll find an artifact at the bottom (zip containing the jar file). You can try this out and should solve the issue.
