### ISSUE TITLE
Mod not working now with BetterNether

### ISSUE THREAD

**Issue by MelZabs** [RakambdaOrg/FallingTree#337]
### Describe the bug

I had the mod on my server and after adding two new mods it isn't working. New mods added were BetterNether and BCLib. Are these mods not compatible with each other?

### Minecraft version

1.18.1

### Fabric API version

0.44.0

### Mod version

3.2.1

**Comment by Rakambda** [comment]
What do you mean by not working anymore?

New tress are not chopped down? New tools are not recognized? Trees that were chopped before are not anymore?...

**Comment by Rakambda** [comment]
Reference to issue opened on BN side : https://github.com/paulevsGitch/BetterNether/issues/534

----

I tried in single player wit the versions you provided, and it works fine. Vanilla trees are still being broken, and new nether trees are too.
=> Maybe it's only when on server?

![image](https://user-images.githubusercontent.com/1688389/162563759-2449c159-6a5a-478b-9891-b531f6241e41.png)

Are you sure your FallingTree is well configured? Like maybe you have the enchantment activated but not on the tool? Or sneaking is reversed and disables the mod?
