### ISSUE TITLE
Add option to break Mangrove Roots

### ISSUE THREAD

**Issue by Rakambda** [RakambdaOrg/FallingTree#339]
### Describe the feature

Title

**Comment by vico93** [comment]
Any updates about this? In my game (1.20.1, Fabric and FT v4.3.0) mangrove roots still arent influenced (neither drop or decay) when cutting a mangrove tree.

**Comment by Rakambda** [comment]
You can open an issue with the details. But someone posted another issue recently and as I checked it does work.
