### ISSUE TITLE
Registry remapping error on client after enabling enchant

### ISSUE THREAD

**Issue by IronPegasus** [RakambdaOrg/FallingTree#343]
### Describe the bug

I am trying to set up a Minecraft 1.18.1/Fabric 0.13.3 server. I have the FallingTree mod (v 3.2.1) added to both my personal client instance and the server. The mod works fine when `"registerEnchant": false` is configured on the server, but when I set it to `"registerEnchant": true` I get the following error message upon trying to connect:

`Registry mapping failed: Received ID map for minecraft:enchantment contains IDs unknown to the receiver! - fallingtree:chopper`
![image](https://user-images.githubusercontent.com/23134437/163461073-4ec4b259-9ea2-43f6-a55c-86f635bf753e.png)

I have attached my full fallingtree.json for you. I don't understand why the client is unable to recognize this enchantment since the mod is present. Is there additional config that I am missing?

## Config

```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 150,
    "maxSizeAction": "CUT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "instantlyBreakWarts": false,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": true,
    "ignoreTools": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.5
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "registerEnchant": true,
    "hideEnchant": false
  },
  "reverseSneaking": false,
  "breakInCreative": true,
  "notificationMode": "ACTION_BAR"
}   
```

### Minecraft version

1.18.1

### Fabric API version

0.13.3

### Mod version

3.2.1

**Comment by Rakambda** [comment]
You also have to turn that configuration (`registerEnchant`) ON on the client.
Both sides need to register the enchant otherwise just one side knows about it and leads to that mismatch.

**Comment by IronPegasus** [comment]
That's going to be terribly inconvenient as I'll have to direct every single one of my players to also adjust their configuration files too. Personally, I don't think that's a reasonable expectation.

Thank you for the response. I'll look into the other settings to see if I accomplish what I want differently.

**Comment by Rakambda** [comment]
Never used it but saw it several times. This may help into what you want to achieve as it seems to be able to supply default custom config files for modpacks : https://www.curseforge.com/minecraft/mc-mods/defaultsettings
