### ISSUE TITLE
more vanilla tools mod does not chop down trees (axes)

### ISSUE THREAD

**Issue by autoclikerboi121** [RakambdaOrg/FallingTree#350]
if you use the more vanilla tools mod with this mod, the axes will not cut down the trees like normal tools do. kinda sucks.:(

### Minecraft version

1.18.2

### Forge version

40.1.19

### Mod version

4.1.1

**Comment by Rakambda** [comment]
Simply whitelist the tools in the config

**Comment by autoclikerboi121** [comment]
Thanks!! Sorry i didn't not know thanks for informing me now I'll do that
