### ISSUE TITLE
Option to disable Dropping Loot on Creative Mode

### ISSUE THREAD

**Issue by ardissaps** [RakambdaOrg/FallingTree#362]
### Describe the feature

Option to yeet the wood loot in creative mode to for cleaner inventory. Thanks!

**Comment by Rakambda** [comment]
That'll work for the logs, however for the leaves it won't. I just random-tick them and therefore don't have the hand on them breaking (and looting) or not.

**Comment by ardissaps** [comment]
Thank you!
