### ISSUE TITLE
Empty Tag does do sh*t in the bad way

### ISSUE THREAD

**Issue by Laifsyn** [RakambdaOrg/FallingTree#367]
### Describe the bug

Having an empty tag will cause Falling Tree to not work
Having this breaks Falling Tree, not letting you to insta mine trees
```
,
  "player": {
    "allowedTags": [
      "",
      ""
    ]
  }
```

### Minecraft version

1.18.2

### Fabric API version

0.56.1

### Mod version

3.5.1

**Comment by Rakambda** [comment]
To me this doesn't sound like a bug. Defining <empty> as a tag is not the same as not defining anything.
That special case will be handled in next versions of FT, so for 1.18 versions you can simply define a proper tag or none.
