### ISSUE TITLE
Item does not automatically stack when picked from ground.

### ISSUE THREAD

**Issue by ardissaps** [RakambdaOrg/FallingTree#372]
### Describe the bug

The item scattered around in inventory like this :
![image](https://user-images.githubusercontent.com/82106625/176083234-ec8883b0-2327-4ef9-bfbc-819ab5a673d5.png)

I don't know if it is problem with Falling Tree or [Stacker](https://modrinth.com/mod/stacker) mod.
I'll post on both page.
https://github.com/Andrew6rant/Stacker/issues/45

### Minecraft version

1.18.2

### Fabric API version

0.14.8

### Mod version

3.5.2

### Relevant log output

```shell
Not crash.
```

**Comment by ardissaps** [comment]
I can confirm it is not from Stacker side, I disabled stacker but problem persist :
![image](https://user-images.githubusercontent.com/82106625/176084570-c76d2e7d-7c6c-412a-ac34-17b3dbb4cf4e.png)

**Comment by Rakambda** [comment]
Seems to be the same as #304.

I never was able to reproduce that issue. 

* Does in happens after a restart?
* Is it in only a specific world or in all of them?

Would you be willing to send a zip with the following folders? mod + world + config

**Comment by ardissaps** [comment]
> Would you be willing to send a zip with the following folders? mod + world + config

Thats very huge. 500MB.
Looklike this is not from Falling Tree either, I disabled both problem still persist.
![image](https://user-images.githubusercontent.com/82106625/176102256-169cea14-2e6d-4ad1-b0e6-fa4cc9011f76.png)
Look like I need to trim the mod half by half. Sorry for your time!

**Comment by Rakambda** [comment]
It's ok no worries.
I'd be interested if you manage to find what mod does this or it's vanilla Mac that has an issue.

Perhaps the NBT data on the logs are different hence why they don't stack up.

**Comment by ardissaps** [comment]
> It's ok no worries. I'd be interested if you manage to find what mod does this or it's vanilla Mac that has an issue.
> 
> Perhaps the NBT data on the logs are different hence why they don't stack up.

Found it! it is from [Pickup Notification](https://modrinth.com/mod/roundaround-pickup-notifications/version/f6ou0Gij), but it is fixed last night.

**Comment by Rakambda** [comment]
Just as a reference, fix has been made with https://github.com/Roundaround/mc-fabric-pickup-notifications/commit/7ad4a61d8cf62fd302fad7d96acd7c00da2b9a89

**Comment by ardissaps** [comment]
Yeah, I installed the mod again, the crafting table bug also caused by that. Now game run perfectly!
