### ISSUE TITLE
Tetra Axes do not fell trees.

### ISSUE THREAD

**Issue by Angular-Angel** [RakambdaOrg/FallingTree#373]
### Describe the bug

I submitted a report for this on Tetra: https://github.com/mickelus/tetra/issues/636

Basically, their axes don't count as axes, and thus don't fell tree's.

### Minecraft version

1.18.2

### Forge version

40.1.22

### Mod version

3.5.1

**Comment by Rakambda** [comment]
You can just add them to the allow list if they are not detected by default.

**Comment by Rakambda** [comment]
Either you'll have to add them one by one, or if they are part of a custom tag, you can add that tag directly.

**Comment by Angular-Angel** [comment]
I'm not sure it's possible to add Tetra Axes as as items, though. I don't know how it works under the hood, but I suspect there's no way to tell a Tetra axe from a Tetra pickaxe or hoe at a surface level - they're all treated the same in the Tetra workbench, and you can turn one into the other, or mix and match between them if you like.

**Comment by Rakambda** [comment]
I see. Indeed mixed tools are an issue here. The whitelist system works based on the item type.

I'm not really sure how things can be solved here 🤔

**Comment by Angular-Angel** [comment]
Is there any kind of dynamic item tag system? So, an individual Tetra tool could be tagged as an axe, and then FallingTree could check for that tag?

**Comment by Rakambda** [comment]
I'm not really sure that exists. Minecraft tags are applied at the item level (basically it's a group of items/blocks). So it may not be relevant in that case if the item is always tetra:the_tool (whether it's in axe mode or pickaxe or whatever).

**Comment by Angular-Angel** [comment]
Oh, wait! Atcually, [Origins: Classes](https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge) has a treechopping ability for the Lumberjack that is able to recognize Tetra axes. So, you could go figure out how they do things and use that? :/

**Comment by Rakambda** [comment]
You can try that version and see how it behaves. It may detect the axe by default (and so if don't want it, just blacklist the whole tool)
[FallingTree-1.18.2-0.0.1-dev.zip](https://github.com/RakSrinaNa/FallingTree/files/9032594/FallingTree-1.18.2-0.0.1-dev.zip)
.

**Comment by Angular-Angel** [comment]
Alright, will do!

**Comment by Angular-Angel** [comment]
No, that version doesn't work at all, so far as I can tell. It does show up in the forge logs as a loaded mod, but it's behavior doesn't trigger with Tetra axes, or with normal axes, or even the fast leaf decay part.

**Comment by Angular-Angel** [comment]
No, wait! I tried to use the zip as a mod. That would do it. :X

**Comment by Angular-Angel** [comment]
Yes! That does it! It works with my normal axe, and my Tetra axe, and *doesn't* work with my Tetra pickaxe! Excellent! XD

**Comment by Rakambda** [comment]
Great, will do an official release of it later today.
