### ISSUE TITLE
Preserve Tool = False not breaking the tools

### ISSUE THREAD

**Issue by reddvilzz** [RakambdaOrg/FallingTree#374]
### Describe the bug

When preserve tool set to False, when the axe have no durability still can be used to break 1 log at a time, even though it is supposed to destroy the tools when it ran out durability.

If I set preserve tool to True, I cannot destroy any log, which is intended because my tool count as doesn't have any durability left. and only outputs "chat.fallingtree.prevented_break_tool" to the chat box.

### Minecraft version

1.12.2

### Forge version

14.23.5.2860

### Mod version

2.4.0

**Comment by Rakambda** [comment]
That version is quite old and I don't usually maintain those.
I still tried to take a look around but all the forge setup for 1.12 changed and I just struggle to get a dev env working.

Sorry to say but I think that issue won't be fixed.

**Comment by reddvilzz** [comment]
oh okay then thank you for the response.
