### ISSUE TITLE
Falling Tree fail to load on start up (versions 2.8+)

### ISSUE THREAD

**Issue by dheivs** [RakambdaOrg/FallingTree#38]
**Describe the bug**
As soon as I launch my Minecraft, an error message will pop up saying that Falling Tree has failed to load correctly.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/72005130/102423983-34577500-4045-11eb-9ad0-07fcc027e92f.png)

**To Reproduce**
1. Put the mod in the mod folder
2. Launch MC
3. Let it simmer
4. VOILA! A brand new crash report!

**Infos:**
 - Minecraft verson: 1.16.4
 - Mod loader: Forge
 - Mod version: 2.8.0

If you provide a crash report please include it in a readable way (like pastebin or gist for example).
Here is the crash report: https://pastebin.com/8ER7m3v6

**Comment by Rakambda** [comment]
Did you install Cloth Config?

![image](https://user-images.githubusercontent.com/1688389/102451546-f9e7db00-4038-11eb-9115-987c36b86f1e.jpeg)

**Comment by Sermanes** [comment]
@RakSrinaNa  How do I install it?  Is there any guide?

**Comment by Rakambda** [comment]
Like any other mod, by dropping its jar into the `mods` folder.

**Comment by smolpemi** [comment]
Hey, I've been trying to install this updated version but I also keep getting the same error even after I've downloaded the cloth-config-forge-4.1.1. Is there any other solutions?

**Comment by Rakambda** [comment]
Weird, I can't manage to reproduce at all.

The mods folder:
![explorer_2020-12-17 17 08 29 559_THVYZZEK1p](https://user-images.githubusercontent.com/1688389/102512819-c170ed00-408a-11eb-9ab1-ebe3eac041de.png)

Minecraft loaded:
![javaw_2020-12-17 17 08 03 458_xEljwgBvyy](https://user-images.githubusercontent.com/1688389/102512860-d0579f80-408a-11eb-83da-d46ae3ac9f43.png)

We're ok that you downloaded ?
* FallingTree: https://www.curseforge.com/minecraft/mc-mods/falling-tree/files/3140671
* ClothConfig: https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/files/3112227

**Comment by smolpemi** [comment]
Wow I have no idea what changed because I was putting the same files in the same location but it's working now! xD Thank you so much!

**Comment by dheivs** [comment]
Hi! Sorry about this. Yes, it works now after adding the cloth config. 

I used to just add this mod alone for a very long time until now.  Thank you.

**Comment by Rakambda** [comment]
Yeah I kinda guessed that this would happen :laughing: 

I added this so that now there's a configuration menu from within the mod menu on the main screen. I guess this is more pleasant than having to go into the conf file.
