### ISSUE TITLE
Add Enchantment Description

### ISSUE THREAD

**Issue by pewblaze** [RakambdaOrg/FallingTree#381]
### Describe the feature

I really love this mod!
I would love if you could add support for Enchantment Description 👍 
https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by Rakambda** [comment]
Will look into it, seems [easy enough to do](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions#how-do-i-add-new-descriptions).

**Comment by Rakambda** [comment]
Can you try [this build](https://github.com/RakSrinaNa/FallingTree/actions/runs/2665015693) ? (In the artifact section you can download a jar that contains the jar/mod file)
