### ISSUE TITLE
Mangrove roots arent breaking

### ISSUE THREAD

**Issue by JamieTheNeko** [RakambdaOrg/FallingTree#382]
### Describe the bug

I have the setting for mangrove roots on, but they wont break at all. i have to go fishing for the wood
![2022-07-13_17 37 24](https://user-images.githubusercontent.com/109233180/178774131-63ff990c-2e0a-4c00-8a3f-dbb6c586e3b4.png)
![2022-07-13_17 37 29](https://user-images.githubusercontent.com/109233180/178774145-fdf80515-13ac-47a8-943d-ec2417cc9d7d.png)
![2022-07-13_17 37 06](https://user-images.githubusercontent.com/109233180/178774155-2e30eb56-977c-4c8f-a72a-ae9e7494943c.png)
.

### Minecraft version

1.19

### Fabric API version

0.55.3

### Mod version

3.6.1

**Comment by Rakambda** [comment]
So if I understand well you're breaking the roots and you expect the whole tree to fall?

If so then this is normal behavior, the roots are considered "leaves" so they are breaking when the associated trunk is destroyed. So that indeed mean you have to reach for it.

If you want to have the root act like it's the trunk you can :
* Add "minecraft:mangrove_roots" to be allowed logs 
* Enable "Allow trunks with mixed logs"

**Comment by Rakambda** [comment]
If you mean that you break the trunk and nothing else disappears, then I can't manage to reproduce it.
Tried with FT 3.7.2 & Fabric 0.56.0+1.19. Can you reproduce with those latest versions?

**Comment by JamieTheNeko** [comment]
> If you mean that you break the trunk and nothing else disappears, then I can't manage to reproduce it. Tried with FT 3.7.2 & Fabric 0.56.0+1.19. Can you reproduce with those latest versions?

i did update it all.. still no change.. the roots dont break with the tree. the leaves do but the roots dont. i will try your fix and let you know

**Comment by Rakambda** [comment]
My "fix" was if you wanted to break the whole tree by breaking a root.

But seems like you bread the trunk.
Can you share your config file?

**Comment by JamieTheNeko** [comment]
> My "fix" was if you wanted to break the whole tree by breaking a root.
> 
> But seems like you bread the trunk. Can you share your config file?

Yeah I wanted to break the whole tree from the trunk. I tried the fix but it only broke the roots and not the trunk. Then I tried it on the allowed leaves too. I'll have to share it a bit later as my power is out

**Comment by JamieTheNeko** [comment]
> > My "fix" was if you wanted to break the whole tree by breaking a root.
> > But seems like you bread the trunk. Can you share your config file?
> 
> Yeah I wanted to break the whole tree from the trunk. I tried the fix but it only broke the roots and not the trunk. Then I tried it on the allowed leaves too. I'll have to share it a bit later as my power is out

I just found a fix. But that might be an issue for you too. It's linked to the nether warts. As soon as I switched it on. It instantly broke the whole tree

**Comment by JamieTheNeko** [comment]
> > > My "fix" was if you wanted to break the whole tree by breaking a root.
> > > But seems like you bread the trunk. Can you share your config file?
> > 
> > 
> > Yeah I wanted to break the whole tree from the trunk. I tried the fix but it only broke the roots and not the trunk. Then I tried it on the allowed leaves too. I'll have to share it a bit later as my power is out
> 
> I just found a fix. But that might be an issue for you too. It's linked to the nether warts. As soon as I switched it on. It instantly broke the whole tree

But still some roots don't break always but I can get that, that's just how it works.

**Comment by Rakambda** [comment]
> I just found a fix. But that might be an issue for you too. It's linked to the nether warts. As soon as I switched it on. It instantly broke the whole tree

So:  
* if you have "Break nether warts" off + "Break mangrove roots" on => Does not break the roots
* if you have "Break nether warts" on + "Break mangrove roots" on => Does break the roots

Correct?

Edit: Ok I manage to reproduce it that way 👍

**Comment by Rakambda** [comment]
Good find, I was basically "tagging" the roots as warts when scanning the tree 😅 

Will make a release in a bit.
