### ISSUE TITLE
[1.19] Enchantment also on other tools

### ISSUE THREAD

**Issue by pewblaze** [RakambdaOrg/FallingTree#385]
### Describe the bug

The Enchantment is also on tools like the pickaxe. 
![grafik](https://user-images.githubusercontent.com/96242065/179736267-dcd5a96a-27c1-4ea7-b238-244e476173a2.png)

### Minecraft version

1.19

### Fabric API version

0.14.8

### Mod version

3.7.4

**Comment by Rakambda** [comment]
Hmm, the enchant should go only on the tools that are whitelisted. It uses the same method as when a tree is cut 🥲

I'll try to see if I can reproduce it later.

**Comment by Rakambda** [comment]
I cannot reproduce.
![image](https://user-images.githubusercontent.com/1688389/179804075-08ac9126-ac3b-4802-a4b7-407399e585af.png)

Either the tool is whitelisted or some mods brings some kind of incompatibility.

**Comment by pewblaze** [comment]
Ah okay, ive got a lot of mods. Maybe i can find out which one does it.

**Comment by Rakambda** [comment]
If that is one. You can try first with just Falling Tree if you manage to reproduce it; I wasn't able to though.

**Comment by pewblaze** [comment]
> So i tried it on a clean install on Fabric (fabric-api-0.58.5+1.19.1) 1.19.1 without any mods and i can enchant for example boots with infinity or feather falling on a pickaxe. Now im not sure if it was always like this? ^^" 
> (I tried to pin the mod down that causes this issue - all the way to only fahttps://cdn.discordapp.cohttps://cdn.discordapp.com/attachments/648385377421492224/1003271159774720100/unknown.pngm/attachments/648385377421492224/1003271159447560243/unknown.pngbric D:)

Nevermind, you can enchant everything in creative. Im sorry, i didnt know that ^^"

**Comment by pewblaze** [comment]
Okay ive got it also in the enchanting table and can enchant a pickaxe with it. ill try to find the mod again ^^"
