### ISSUE TITLE
Cannot tell what version of Forge the mod works with and need to find a version compatible with a specific forge version.

### ISSUE THREAD

**Issue by WillTereika** [RakambdaOrg/FallingTree#387]
### Describe the bug

So I'm trying to add this into a modpack, the rest of the modpack uses o41.0.45 of Forge, but the latest file of this mod requires a later version.. How am I supposed to tell which version of Forge what file is for, because It does not say ANYWHERE on the Forge site.  Just looking for some help, thanks.

### Minecraft version

1.19

### Forge version

41.0.45

### Mod version

1.19-3.7.4

### Relevant log output

```shell
E]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §efallingtree§r requires §6forge§r §o41.0.94 or above§r
§7Currently, §6forge§r§7 is §o41.0.45
```

**Comment by Rakambda** [comment]
You can have a look at the changelog which gives info about this.

![image](https://user-images.githubusercontent.com/1688389/179902168-3732bed3-3cd6-464e-8ee1-040f0777b764.jpeg)

3.7.0 should work with older forge.
