### ISSUE TITLE
Issue with custom speed

### ISSUE THREAD

**Issue by DelphiDv** [RakambdaOrg/FallingTree#39]
Even with the mod install on both the client and server, i still get the weird _block not breaking when mined and tree taking a full minute to fall_ issue, am i doing something wrong?

**Comment by Rakambda** [comment]
So what I'm guessing is that you have modified the configuration `speedMultiplicand`?

If that value is set to something else than `0` then it is normal that it takes longer to break the tree.

"Block not breaking when mined" I guess you break the block, but the tree itself doesn't fall along with it? If so, and that you modified `speedMtiplicand`, you'll have to set the same value both in the server & client config. Minecraft do the calculation of the sped to break the block independently on each side. If you have a different value then one side will think it's broken even though it's not.
