### ISSUE TITLE
The non-instantaneous option not working

### ISSUE THREAD

**Issue by 5hinySylveon** [RakambdaOrg/FallingTree#396]
### Describe the bug

Instantaneous option still active despite changing it to Shift Dow

https://user-images.githubusercontent.com/106100669/184448214-b989d60b-6faf-4a2e-98c5-dd19599da995.mp4

n

### Minecraft version

1.19.2

### Fabric API version

0.59.0

### Mod version

3.9.1

**Comment by Rakambda** [comment]
If you restart the game, does it stay as being SHIFT_DOWN?

**Comment by 5hinySylveon** [comment]
Restarting the game did fix it and now I feel dumb

**Comment by Rakambda** [comment]
Though that is indeed an issue i'll look into. Switching from Insta to shift down doesn't apply the settings immediately.

This is probably linked to the changes made for #360

**Comment by Rakambda** [comment]
Local saves were considered as being a server, so when you log in into your world it pulled the config values from the "server". When you changed them through mod menu, it indeed changed your local config but didn't update the "server" values.

Restarting the game basically made the "server" part reload the config from the file.

Though, you only need to get out of your world and get back in, no need to fully restart minecraft. A fix will be coming 👌
