### ISSUE TITLE
Don't chop player placed logs

### ISSUE THREAD

**Issue by Yamza** [RakambdaOrg/FallingTree#4]
Basically have had this happen a few times. A player went to chop one log off the house and the whole house is gone. Would it be possible to prevent this?

https://i.imgur.com/z0cquzL.jpg
https://i.imgur.com/Z1Sq1UJ.jpg

**Comment by Rakambda** [comment]
There is an option to no activate the mod when chopping down to have just one log being destroyed (the default behavior). Just have to cut it while sneaking (can be reversed in the config to only destroy all when sneaking).
I don't think there's a way for me to distinguish between generated logs and those placed by a player.

**Comment by Yamza** [comment]
Swear I've seen something like that before. If I end up finding what did it I'll get back to you. Thank you for considering it!
