### ISSUE TITLE
Several Tool tips left aligned of the cursor in the config menu

### ISSUE THREAD

**Issue by utechtl** [RakambdaOrg/FallingTree#40]
**Describe the bug**

**To Reproduce**
1. Mods -> Falling Tree -> Config
2. Hover over various options.

Affected options are:
Reverse Sneaking- depends if the mouse is hovering over reverse it's fine but if it's over the sneaking part then it's unreadable
All of the Trees options except "Trunk Breaking"
All of the Tools Options.

**Infos:**
 - Minecraft verson: 1.16.4
 - Mod loader: Forge 35.1.4
 - Mod version: 2.8.0

![Full screen](https://user-images.githubusercontent.com/1733500/102703353-43037f00-4233-11eb-8b0d-710c09363451.png)

![Hovering over reverse](https://user-images.githubusercontent.com/1733500/102703356-472f9c80-4233-11eb-917a-38bc91793f8e.png)

![Hovering over sneaking](https://user-images.githubusercontent.com/1733500/102703358-48f96000-4233-11eb-888c-1342243f7e3d.png)

**Comment by Rakambda** [comment]
I reduced the length of the lines. It should now fit a bit better on screen. Will be in version `2.8.1`.
