### ISSUE TITLE
Config option to disable tree-punching

### ISSUE THREAD

**Issue by Rekonin** [RakambdaOrg/FallingTree#403]
### Describe the feature

For better integration with other progression-altering mods

**Comment by Rakambda** [comment]
Can you elaborate?

**Comment by Rekonin** [comment]
I don't how how to simplify it more.
An option that would disable the punching of trees to gather them. So only tools would work on logs

**Comment by Rakambda** [comment]
I see, so basically the trunk would not break and stay in place if no tools are used, right?

**Comment by Rekonin** [comment]
Correct.
The idea being that it would help your mod fit in with others that add things like ground sticks/stones or flint tools. Or simply forcing you to search for a village. Off by default I'd suggest though.
Just an idea, as none of the other mods that do this are updated past 1.18.2 atm

**Comment by Rakambda** [comment]
I can add this, however you mention 1.18.2. I won't be adding new features to that version, will only be added to 1.19.2 and therefore available for versions after that.
I guess it won't really "fix" what you're looking for as you'll have to wait for other mods to update but hopefully it'll be useful in for potentially next modpack updates.

**Comment by Rekonin** [comment]
As long as it makes sense to you to put in your mod.
No, I'm putting together a modpack for 1.19.2 and have most of the other stuff.
I figure most other mod devs are waiting to see if .2 is the last iteration before updating

**Comment by Rakambda** [comment]
You can try this 1.19.2 version and see if it fits your needs.
The mod is inside a zip fil you can download under assets : https://github.com/RakSrinaNa/FallingTree/actions/runs/2983549901

**Comment by Rekonin** [comment]
Well it certainly stops you breaking logs!
But it also stops you breaking _everything_ with your hands, dirt, sand, even grass/flowers

**Comment by Rakambda** [comment]
Indeed, didn't think of that 😆 
Should be better with that build, will only be applied to whitelisted blocks : https://github.com/RakSrinaNa/FallingTree/actions/runs/2984690102

**Comment by Rekonin** [comment]
Been having a play and that seems to be it!
I added 'Oh The Biomes You'll Go' as a test for all the custom added trees and it's working with those fine too.

What do you mean by the whitelisted blocks though? I haven't added in anything in whitelist or blacklist and it seems to be doing things correctly... unless I'm missing something

**Comment by Rakambda** [comment]
Whitelisted blocks are the blocks considered as logs.

By default most logs are recognized. But if let's say you add `minecraft:sponge` in that list, then you'll be denied breaking it too (as it's considered a log).

**Comment by Rekonin** [comment]
Gotcha!
And would additional whitelisted blocks _all_ need to be individually added or would wildcards work?
For instance "*planks", "*stairs" etc?

**Comment by Rakambda** [comment]
The way it is done is to restrict "logs" from being broken by a tool. Not to restrict "any arbitrary set of blocks" to be broken.
Stairs etc are out of scope of FallingTree which is focused on tree.

If you add them to the whitelist, then yeah you'd have to do it manually, but also you'd have weird behaviors. Like it's mean that trees can be made of stairs. And if someone uses an axe on a row of stairs.... it'll be chopped in one go.

**Comment by Rekonin** [comment]
Oh yea, stairs wasn't a good example now I think about it, seeing as stone-types exist.

So basically, I'll just load in creative, search inventory for and place one of every log in my pack, switch to survival mode and attempt to punch all of them. Then _if_ any of them allow me to break them for whatever reason, add those to the config list.

You've been super helpful and this is great, ty so much for going with it!
