### ISSUE TITLE
Reverse sneaking not working as intended ?

### ISSUE THREAD

**Issue by Andibyts** [RakambdaOrg/FallingTree#41]
**Describe the bug**
When Reverse sneaking is activated it cuts down trees while shifting and also while not shifting
**To Reproduce**
1. activate Reverse sneaking
2. cut down a tree while sneaking and while not

**Infos:**
 - Minecraft verson: 1.16.4
 - Mod loader: Forge
 - Mod version: 2.8.1

**Comment by Rakambda** [comment]
I can't reproduce that :/

**Comment by Andibyts** [comment]
Thats strange, i also realised that even if I have a minimum of 1 leave for it to cut, it still cuts logs with no leaves at all

**Comment by Rakambda** [comment]
Do you play with other mods? Maybe there's an imcompatibility?

**Comment by Andibyts** [comment]
I do, I will try it just with your mod right now

**Comment by Andibyts** [comment]
Okay, seems to be a incompatibility with another mod. But 70 Mods are to many to test which one it is right know

**Comment by Rakambda** [comment]
Yeah for sure will be hard to pint point which one it is.
But if at some point if you manage to find which one it is I'm interested knowing it.

Even though I'm not sure if I can't fix that as I get the sneaking status from Forge.

**Comment by Andibyts** [comment]
I will take some time tomorrow and test it. Will let you know if I found out more
