### ISSUE TITLE
Client crash when I want chop a big tree...

### ISSUE THREAD

**Issue by zanecek** [RakambdaOrg/FallingTree#435]
### Describe the bug

[fallingtree-crash-2022-10-24_03.01.38-client.txt](https://github.com/Rakambda/FallingTree/files/9894768/fallingtree-crash-2022-10-24_03.01.38-client.txt)

### Minecraft version

1.16.5

### Forge version

36.2.39

### Mod version

FallingTree-2.11.5

**Comment by Rakambda** [comment]
What about this version (the mod jar-file is in the zip)
[FallingTree-1.16.5-2.11.5.zip](https://github.com/Rakambda/FallingTree/files/9895370/FallingTree-1.16.5-2.11.5.zip)

**Comment by zanecek** [comment]
This new version is working fine for me so far...
