### ISSUE TITLE
option for player exhaustion

### ISSUE THREAD

**Issue by scarf005** [RakambdaOrg/FallingTree#443]
### Describe the feature

an option to control how much fatigue player get from chopping tree with fallingtree:
for example:
`1.0 (default)`: same as vanilla tree-chopping.
`10.0`: chopping tree makes you ten times more hungry

**Comment by Rakambda** [comment]
This is actually somewhat handled. It is linked to the damageMultiplicand. For example, if you set it to 10, it'll act as if you used your tool 10*\<number of logs\> times, and therefore minecraft will deduce the saturation for that number of broken blocks).

It could have a different setting but not sure it makes sense to me, I'd prefer have minecraft manage this by itself.
To me having the "cost of using the mod" as tool damaging is more interesting than player fatigue. Unless you have a use case for this that makes sense and can't be replaced with the damage feature, i probably won't do it.
