### ISSUE TITLE
Tool whitelist in 1.12.2 not working

### ISSUE THREAD

**Issue by BloodyRain2k** [RakambdaOrg/FallingTree#46]
**Describe the bug**
No matter what and how I enter in the whitelist for the tools (or the blacklist for that matter) it will only save an empty list.

**To Reproduce**
1. Enter the mod's settings in the main menu
2. Enter the 3rd submenu of the 3x "falling_trees" (see screenshot)
3. Enter various tools into the whitelist, in my case "tconstruct:hatchet", "tconstruct:lumberaxe", "tconstruct:mattock"
4. Press "Done" until back in the mod list
5. Enter the mod's settings again => "Reset" button for the settings still greyed out because nothing was saved : (

**Infos:**
 - Minecraft verson: 1.12.2
 - Mod loader: Forge 14.23.5.2854
 - Mod version: 2.4.0

![image](https://user-images.githubusercontent.com/1014362/103478726-f68a7880-4dc8-11eb-989b-4084a23440a6.png)

Edit 1: I just tried the version released before this one and there it works.
But the 'release' version of the mod can neither load nor save these settings : (

Edit 2: However, with this version is the problem that it doesn't care about what it's loading -_-

**Comment by Rakambda** [comment]
I can reproduce it.
Seems like the config of the `general` category is saved fine. However the other ones (`trees` & `tools`) aren't.

Now I'm not sure if I really want to invest time into fixing it. I'm using Forge's configuration annotations which delegates the configuration handling to Forge. I don't really know if I set it up a bit wrongly or if it doesn't handle well `config categories` but I couldn't find anything that fixed it without trying to dig in too deep.

1.12.2 is also quite old and not really a big fan of updating old versions. 
But having a GUI that doesn't do what it is supposed to isn't really better.
So I'm not too sure if I should let it like that, or just remove the GUI (that is generated by forge and that I never really intended to support (it is supported & working but in 1.16.4+ versions)) somehow.

**Comment by BloodyRain2k** [comment]
I wouldn't mind if I had to edit the file externally to make the loading work, but even that is thrown away.
There's another mod with almost the same bug, except that it at least loads the settings fine.

But when I edit them here externally they won't even be loaded into the ingame settings, so not even that seems to work.

**Comment by Rakambda** [comment]
Yeah that part isn't normal though, I'll look into it

**Comment by Rakambda** [comment]
Editing the file works for me.

* Close Minecraft
* Edit `falling_tree.cfg`
* The section you're refereeing to should look like (with the id being those you want):
```cfg
    # Additional list of tools that can be used to chop down a tree.
    # INFO: Items marked with the axe tag will already be whitelisted.
    S:whitelisted <
        minecraft:dirt
        minecraft:iron_block
     >
```

**Comment by BloodyRain2k** [comment]
Ahhh, that's why nothing worked...
Stupid Forge-Config formatting <_<

I've tried pretty much all formats, except one entry per line withOUT the , at the end.
Now it works fine :facepalm:

With this the issue is pretty meh, if anyone else happens to run into it, here's the solution then xD

Thanks for your time :+1:
