### ISSUE TITLE
Chopper enchantment to work as improvement

### ISSUE THREAD

**Issue by Dekamir** [RakambdaOrg/FallingTree#462]
### Describe the feature

A configurable option can be in the mod.

If this option is enabled, players can fell the trees even if they don't have the chopper enchantment, but they would do it slowly (according to the main speed multiplier).
And if the player enchants their Axe with Chopper, it breaks as if the multiplier is 0 (or also configurable).

**Comment by Rakambda** [comment]
I don't think it'll be done. I guess people just won't break with the mod (break vanilla style) when they don't have the enchantment, and when they do, then the mod is applied with the appropriate mode.
