### ISSUE TITLE
Speed Multiplier just not works

### ISSUE THREAD

**Issue by Landrozaum** [RakambdaOrg/FallingTree#474]
### Describe the bug

Speed Multiplier doesn't works, i changed it to "1" and nothing changed in the speed of breaking trees, the chop mod is instantaneous btw.

### Minecraft version

1.19.2

### Fabric API version

0.14.12

### Mod version

3.10.0

### Relevant log output

```shell
-no crashes happened-
```

**Comment by Rakambda** [comment]
Playing on a server or singleplayer ?
