### ISSUE TITLE
Not working with custom trees

### ISSUE THREAD

**Issue by Charm8er** [RakambdaOrg/FallingTree#475]
### Describe the bug

I tried using this with custom trees that I made for a new server and it doesn't seem to be working....  I added some of the custom blocks used in the trees in the config file and enabled the mixed logs option to test it out but I can't seem to get it to work.  Please let me know if I am doing something wrong.  Thank you.

### Minecraft version

1.18.2

### Forge version

40.1.54

### Mod version

3.5.4

### Relevant log output

```shell
{
  "trees": {
    "allowedLogs": [
      "conquest:acacia_log_stump",
      "conquest:mossy_acacia_log_stump",
      "conquest:acacia_log_pillar",
      "conquest:acacia_log_branch",
      "conquest:acacia_branch_tip",
      "conquest:acacia_branch_tip_2",
      "conquest:acacia_branch_tip_2_45",
      "conquest:diagonal_acacia_branch_67"
    ],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": true,
    "breakNetherTreeWarts": true,
    "instantlyBreakWarts": false,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "registerEnchant": false,
    "registerSpecificEnchant": false,
    "hideEnchant": false
  },
  "sneakMode": "SNEAK_DISABLE",
  "breakInCreative": false,
  "notificationMode": "ACTION_BAR"
}
```

**Comment by Charm8er** [comment]
Update: I figured for testing purposed I would try it out on default minecraft trees and those dont seem to be working either.  I exported the map using worldpainter, that wouldnt cause this would it?

**Comment by Charm8er** [comment]
I got it to work!  But I don't understand why.  When trying to edit the file in Sublime it doesn't work.  But if I use the ModList config UI, it does...  The file looks identical each way, so I am not sure what is happening here.

**Comment by Rakambda** [comment]
That's indeed weird. Can you perhaps upload both files (one that works from the GUI, and one that doesn't work from Sublime)?
