### ISSUE TITLE
Speed multiplicand doesn't prolonge breaking time using the mode server-side only

### ISSUE THREAD

**Issue by gnapiorkowski** [RakambdaOrg/FallingTree#510]
### Describe the bug

I use this mod server side only and changing Speed multiplicand doesn't change break time, it just adds delay from when I break to log, to when the logs actually drop.

### Minecraft version

1.19.3

### Fabric API version

0.14.17

### Mod version

3.11.2

**Comment by Rakambda** [comment]
Speed multplicand and enchants require the mod to be on the client as well.
Otherwise you'll have a desync like you're experiencing.
