### ISSUE TITLE
Not working on realm

### ISSUE THREAD

**Issue by mnewton2500** [RakambdaOrg/FallingTree#517]
### Describe the bug

Mod was working yesterday on a realm with a friend, today it would not work. Tried rebuilding the mod pack and nothing. I have no idea about configs or how to even access them, I just plug and play what works. thanks for the help.

### Minecraft version

1.19.4

### Fabric API version

0.14.18

### Mod version

1.19.4-3.12.1jar

**Comment by Rakambda** [comment]
Duplicate of #128
Mod needs to be server-side and as far as I know you don't have access to server files on a realm. Hence you can't install fabric and mods on the server.

**Comment by mnewton2500** [comment]
> Duplicate of #128 Mod needs to be server-side and as far as I know you don't have access to server files on a realm. Hence you can't install fabric and mods on the server.

ok thank you, it was really strange i thought i had it work at one point but its likely im wrong.
