### ISSUE TITLE
Cloth Config Server Crash

### ISSUE THREAD

**Issue by WenXin20** [RakambdaOrg/FallingTree#52]
**Describe the bug**
- The newest update crashes the server.

**To Reproduce**
1. Load mod on server.
2. Crash.

**Infos:**
 - Minecraft v1.16.4
 - Mod loader: Forge v31.1.28
 - Mod version: v2.8.2

[Crash Report](https://gist.github.com/WenXin20/3f56fcaaf30a3553e3c93678547ae87b)

**Comment by Rakambda** [comment]
I'll put a better way of handling that in the next version.

Though if you have cloth-config-forge installed on the server, you can remove it. It isn't needed as it just generate GUIs.

**Comment by WenXin20** [comment]
Ah, alright, thanks
