### ISSUE TITLE
Make leaves "simulate" decay instead of dropping themselves as items on FALL_BLOCK mode

### ISSUE THREAD

**Issue by vico93** [RakambdaOrg/FallingTree#566]
### Describe the feature

Basically, in `FALL_BLOCK` mode leaves, instead of dropping themselves as their item form, should "simulate" decaying, dropping its related items (like apples and saplings) instead.

If that tweak is done, this mod would be identical of the old Timberjack mod that i mentioned in #559.

**Comment by Rakambda** [comment]
They should drop their "content".
I'm not really sure to understand d what you get, nothing or the leaf block itself?

**Comment by vico93** [comment]
> They should drop their "content". I'm not really sure to understand d what you get, nothing or the leaf block itself?

I got spammed with leaf block because when chopping the tree almost all leaves drop themselves instead of the items that normally would drop when the leaf naturally decays.

**Comment by Rakambda** [comment]
You have silk touch, right?

**Comment by vico93** [comment]
No, i'm not any enchanted tool to chop trees (even the enchantments option of the mod is disabled, fyi).

Let me try to be more clear clear: When we set the mod to use FALL_BLOCK mode, when chopping a tree, some of the leaves, when falling, drop themselves as items and not decay into things like saplings, apples, or anything on their drop table:

https://github.com/Rakambda/FallingTree/assets/3485505/25a6ec87-ea6f-4083-b755-b62ffcae4d1a

This effect is even shown in the gif on the repository README (right panel):
![image](https://github.com/Rakambda/FallingTree/raw/minecraft/1.20.1/assets/demo2.gif)

What i'm looking for is kinda an "hybrid" mode between FALL_ITEM and FALL_BLOCK: logs and leaves by default with the behavior of FALL_BLOCK (acting like falling sand when chopped), while the other leaves that cant find a place to land, instead of dropping themselves, should decay into saplings or apples, depending of how the leaf block would behave when decaying on vanilla.

**Comment by Rakambda** [comment]
I see, I'm not sure I'll be able to do anything about it though. The thing is, all blocks are transformed into falling entities (same as falling sand etc), so it'll drop the block itself and I have no control over it.

One solution would be to make my own falling entity like TreeChopper but that'd break the server-side only aspect of the mod so I'm not sure I'd do it.

Another possibility is to say that the leaves never drop as a block form on the ground, and act like the FALL_ITEM (as I can't know in advance which will have a spot to land on). FALL_ITEM breaks the item directly and what you see falling is basically just "a ghost" for the visual effect.

**Comment by vico93** [comment]
> I see, I'm not sure I'll be able to do anything about it though. The thing is, all blocks are transformed into falling entities (same as falling sand etc), so it'll drop the block itself and I have no control over it.
> 
> One solution would be to make my own falling entity like TreeChopper but that'd break the server-side only aspect of the mod so I'm not sure I'd do it.
> 
> Another possibility is to say that the leaves never drop as a block form on the ground, and act like the FALL_ITEM (as I can't know in advance which will have a spot to land on). FALL_ITEM breaks the item directly and what you see falling is basically just "a ghost" for the visual effect.

So, what about an hybrid mode where logs act like FALL_BLOCK and leaves FALL_ITEM? Would preserve game consistency since leaves actually can be only pickable using silk touch tools, and also would prevent inventory spam of leaf blocks...

**Comment by Rakambda** [comment]
You can try [this build](https://github.com/Rakambda/FallingTree/actions/runs/5493424346)
