### ISSUE TITLE
Better SHIFT_DOWN visuality

### ISSUE THREAD

**Issue by Disketaa** [RakambdaOrg/FallingTree#574]
### Describe the feature

**Shift-down** mode in **Falling Tree** is a bit similar to multiplayer breaking block lag.
I love this mode more then others, it's better suits vanilla-like experience, but it's have some lack of user experience in my opinion.

Hm, maybe just extra particles or with every shifted block some of leaves will fall as well, it also will combines with Falling Leaves mod to create visual effect like "something happened when I destroy a tree block".

I drew a hard one solution, but it might be the best one if we talking about visual impact
![Breaking](https://github.com/Rakambda/FallingTree/assets/76956762/5054c827-a8ad-4f68-a29c-050931cde534)

**Comment by Rakambda** [comment]
There's several things to consider:

* The leaves don't really have any special processing : they are just randomticked manually when a log is removed near them or another leaf disappears
* Visual animations are limited to whatever vanilla Minecraft provides. This mod is made to be server-side only as much as possible. Adding new visual effects would require the client to also have the mod.
* Multiplayer, what if 2 players are breaking the same tree at the same time, how do you perform the animation.

**Comment by Disketaa** [comment]
Understood. Check out that variant

![15](https://github.com/Rakambda/FallingTree/assets/76956762/39d49e67-cf3c-4225-abb4-359b01189d23)

**Comment by Rakambda** [comment]
That'd be doable I guess

**Comment by Rakambda** [comment]
You can try this build https://github.com/Rakambda/FallingTree/actions/runs/5630991278
