### ISSUE TITLE
Mod Crashes - Prevents Server from Starting

### ISSUE THREAD

**Issue by NicolasS98** [RakambdaOrg/FallingTree#579]
### Describe the bug

The mod crashes and prevents my modded server from starting. I get the below message from the crash report: 
"Failure message: FallingTree (fallingtree) has failed to load correctly", and:
"Exception message: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $".
 
The mod was working correctly one night, and then not the next morning without any changes to what I added on.

Im using forge not fabric but the version is: 

### Minecraft version

1.20.1

### Fabric API version

1.20.1

### Mod version

1.20.1-4.2.4

### Relevant log output

```shell
Exception message: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

Im not sure if this helps. This is my first time using this site, thank you for your time.
```

**Comment by Rakambda** [comment]
Can you share the content of your config file? (`fallingtree.json`)

**Comment by NicolasS98** [comment]
I looked at the config file and for some reason "null" was in the first line where 

"{
  "trees": {"

should've been. After I entered the correct line and saved it, the mod worked and my server would start up correctly. I never changed that line in the config so I'm unsure how that even got there.

**Comment by Rakambda** [comment]
No idea what could have caused it.
