### ISSUE TITLE
Conflict with Natures Aura Ancient trees

### ISSUE THREAD

**Issue by Darkere** [RakambdaOrg/FallingTree#6]
**Describe the bug**
Growing an ancient tree from natures aura with 
`break_leaves = true`
It causes all leaves to break when the tree grows.
**To Reproduce**
1. plant ancient tree and use bonemeal to grow it
2. 

**Infos:**
 - Minecraft verson: 1.15.2
 - Mod version: FallingTree-1.15.2-2.0.3+19

**Comment by Rakambda** [comment]
Sorry didn't see it, I'll see what I can do
