### ISSUE TITLE
Fall Items & Fall Blocks Not An Option

### ISSUE THREAD

**Issue by Cyranos** [RakambdaOrg/FallingTree#606]
### Describe the bug

As per the title, when using the mod config in minecraft to try to set the break mode to either fall items & fall blocks they don't show up the only options that do show up are "INSTANTANEOUS" and "SHIFT_DOWN" and if I manually change the config to add "FALL_ITEM" like how the wiki shows it doesn't work in game and only instead works like shift down.

I have also found out changing;
"breakMode": "INSTANTANEOUS"
Too
"breakMode": "FALL_ITEM"

And
"breakOrder": "CLOSEST_FIRST"
Too
"breakOrder": "LOWEST_FIRST",

Upon next launch of the minecraft instance to have those values removed entirely and crashing the game upon trying to break a tree. Of which you can see the crash log [here](https://mclo.gs/Xvuo2Mp)

### Minecraft version

1.19.2

### Forge version

43.3.0

### Mod version

3.10.0

### Configuration

```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxSizeAction": "ABORT",
    "breakOrder": "CLOSEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "instantlyBreakWarts": false,
    "breakMangroveRoots": true,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "damageMultiplicand": 0.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0,
    "forceToolUsage": false
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "registerEnchant": false,
    "registerSpecificEnchant": false,
    "hideEnchant": false
  },
  "sneakMode": "SNEAK_DISABLE",
  "breakInCreative": false,
  "lootInCreative": true,
  "notificationMode": "ACTION_BAR"
}
```

**Comment by Rakambda** [comment]
Use latest mod version for that Minecraft version. 3.13.0.

**Comment by Rakambda** [comment]
My bad, 3.13.0 is for 1.19.4.
These new features were not backported to 1.19.2.
#594
