### ISSUE TITLE
Compatability with many tree mods:

### ISSUE THREAD

**Issue by ImpulsiveLass** [RakambdaOrg/FallingTree#616]
### Describe the feature

Falling tree only works well if a tree is all strictly the log itself, this results in many mods including BOP, BYG, Alex's Caves, Wilder Wild, and many many others have issues when trees contain more than one specific wood block to make them up.

I am unsure if this would be possible as it may require large changes to the mod, but it would make it soooooooooo much nicer to use in modpacks.

Thank you for your time.

**Comment by Rakambda** [comment]
This is already possible. In the settings, under trees, you should have an option like "allow mixed logs".

**Comment by ImpulsiveLass** [comment]
Just tried that out, did not change anything

**Comment by Rakambda** [comment]
Can you provide your config and the mod you're trying it with?

**Comment by ImpulsiveLass** [comment]
I tested it with the pewen and thornwood trees of Alex’s caves. All I changed in the config was replace the false after allow mixed logs with true

**Comment by Rakambda** [comment]
The top block isn't a leaf (not tagged `#minecraft:leaves`).
![image](https://github.com/RakambdaOrg/FallingTree/assets/1688389/68d5be57-b203-4e8e-b249-adebae2fff28)

So the beavior is coherent with the config.
![image](https://github.com/RakambdaOrg/FallingTree/assets/1688389/69f9130d-fb77-4b4d-8673-746fbafce773)

Either you can set this value to 0, and therefore take the risk of potentially chopping down a house made of logs, or you'll have to define those pines as being leaves in the FT config.

Same goes for the thornwood.

**Comment by ImpulsiveLass** [comment]
Ah I see, would the other woods need to be added manually too or nah since they are tagged as logs?

**Comment by Rakambda** [comment]
Logs seems to be fine as they are tagged with ˋ#minecraft:logs`, only the leaves seems to cause issues as by default FT required one to be present at the top of the tree for security.

**Comment by ImpulsiveLass** [comment]
Tested more extensively, I made the pewen branches and thornwood branches tagged as leaves and made sure all the wood involved are tagged as logs and it works 100% of the time with pewen (other than a few little floating bits that didn’t auto break) and the thorn wood was variable, I imagine it’s because some parts connect on an angle so technically no blocks are next to each other? If there is a config to make it ignore a block gap then I can test it more later (in lecture now :( )

**Comment by Rakambda** [comment]
Diagonal blocks are handled. Leaves are not broken as part of the tree, they simply are random ticked faster. It may happen that sometimes they get stuck (same as with vanilla minecraft, it happens sometimes)

**Comment by ImpulsiveLass** [comment]
Hmm, I’ll check all the tags on the blocks again, maybe I missed something (or maybe I was shifting when a tree didn’t work since I never tested in creative oop)
