### ISSUE TITLE
Tree from "Deeper and Darker" mod doesn't completely fall

### ISSUE THREAD

**Issue by MiniRaptor** [RakambdaOrg/FallingTree#633]
### Describe the bug

In Deeper and Darker mod there a trees with glowing blocks. If you will try to cut this trees, it will fall not fully, glowing blocks will still remain in sky.
![2023-11-27_18 14 21](https://github.com/RakambdaOrg/FallingTree/assets/69641100/34b9fca3-05e3-45e2-a88e-f75d54ae9a66)
![2023-11-27_18 14 24](https://github.com/RakambdaOrg/FallingTree/assets/69641100/a8444c77-ea77-41fa-aab1-39a44887b961)

### Minecraft version

1.20.1

### Fabric API version

0.90.7

### Mod version

4.3.1

### Configuration

```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "FALL_ITEM",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "breakMangroveRoots": true,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0,
    "forceToolUsage": false
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "registerEnchant": false,
    "registerSpecificEnchant": false,
    "hideEnchant": false,
    "requireEnchantment": false
  },
  "sneakMode": "SNEAK_DISABLE",
  "breakInCreative": false,
  "lootInCreative": true,
  "notificationMode": "ACTION_BAR"
}
```

**Comment by MiniRaptor** [comment]
Tree id: deeperdarker:echo_sapling

**Comment by MiniRaptor** [comment]
Glowing block id: deeperdarker:sculk_gleam

**Comment by Rakambda** [comment]
I guess this is the normal behavior of the tree. If you cut it (without FT), leaves will decay but not the glowing part.
FT just accelerates the random ticking on leaves.

Does it change anything if you add that glowing block in the configuration for "allowed log blocks" and enable "mixed log" ? (If they're attached to the tree I guess it'd work, but not if attached to leaves).

**Comment by Rakambda** [comment]
Actually I just remembered but there's a config `allowedNonDecayLeaves`, you should be able to add the `deeperdarker:sculk_gleam` in there and it should work fine

**Comment by MiniRaptor** [comment]
> Actually I just remembered but there's a config `allowedNonDecayLeaves`, you should be able to add the `deeperdarker:sculk_gleam` in there and it should work fine

I will try

**Comment by MiniRaptor** [comment]
> Actually I just remembered but there's a config `allowedNonDecayLeaves`, you should be able to add the `deeperdarker:sculk_gleam` in there and it should work fine

Not work

**Comment by Rakambda** [comment]
Ok, it works only if the lights are connected to the tree, I'll have to fix it

**Comment by Rakambda** [comment]
Can you try this version, still with the `allowedNonDecayLeaves` configured. (mod is inside the zip file)
[FallingTree-1.20.1-4.3.1-1.jar.zip](https://github.com/RakambdaOrg/FallingTree/files/13491522/FallingTree-1.20.1-4.3.1-1.jar.zip)
