### ISSUE TITLE
A problem in the configuration

### ISSUE THREAD

**Issue by Fik13531** [RakambdaOrg/FallingTree#661]
### Describe the bug

Hello, if you could help me tell or show me how to reconfigure `break_order=LOWEST_FIRST` in version 1.12.2, because in my world I would like the blocks to fall as a whole instead of destroying and dropping items or destroying them from below.

### Minecraft version

1.12.2

### Forge version

14.23.5.2856

### Mod version

8.0.99.99

### Configuration

```json
# Configuration file

general {
    # When set to true, the mod will cut down trees in creative too.
    B:break_in_creative=false

    # When set to true, a tree will only be chopped down if the player is sneaking.
    B:reverse_sneaking=false
}


tools {
    # List of tools that should not be considered as tools.
    # INFO: This wins over the whitelist.
    S:blacklisted <
     >

    # Defines the number of times the damage is applied to the tool.
    # ie: if set to 1 then breaking 5 logs will give 5 damage.
    # ie: if set to 2 then breaking 5 logs will give 10 damage.
    # If set to 0, it'll still apply 1 damage for every cut.
    # INFO: This only applies when the tree is cut when using the mod.
    # Min: 0
    # Max: 2147483647
    I:damage_multiplicand=1

    # When set to true, the mod will be activated no matter what you have in your hand (or empty hand).
    # INFO: Blacklist still can be use to restrict some tools.
    B:ignore_tools=false

    # When set to true, when a tree is broken and the tool is about to break we will just break enough blocks so that the tool is left at 1 of durability.
    B:preserve=false

    # Applies a speed modifier when breaking the tree.
    # 0 will disable this, so the speed will be the default one of breaking a block.
    # If set to 1 each log block will be counted once, so if the tree is 5 blocks tall it'll require the time of breaking 5 logs.
    # If set to 2 each log block will be counted twice, so if the tree is 5 blocks tall, it'll require the time of breaking 10 logs
    # INFO: Only in INSTANTANEOUS mode.
    # WARNING: If you are on a server, this either has to be set to 0 or every player should have the mod. Else they'll have a weird effect of breaking the block but the block is still there.
    # Min: 0.0
    # Max: 50.0
    D:speed_multiplicand=0.0

    # Additional list of tools that can be used to chop down a tree.
    # INFO: Items marked with the axe tag will already be whitelisted.
    S:whitelisted <
     >
}


trees {
    # When set to true this allow to have any kind of log in a tree trunk.
    # Otherwise (false) the trunk will be considered as being only one kind of log.
    B:allow_mixed_logs=false

    # How to break the tree.
    # Instantaneous will break it in one go.
    # Shift down will make the tree fall down as you cut it, so you still have to break x blocks but don't have to climb the tree for them.
    # Valid values:
    # INSTANTANEOUS
    # SHIFT_DOWN
    S:break_mode=INSTANTANEOUS

    # List of blocks that should not be considered as leaves.
    # INFO: This wins over the whitelist.
    S:leaves_blacklisted <
     >

    # When set to true, leaves that should naturally break will be broken instantly.
    B:leaves_breaking=true

    # Radius to force break leaves. If another tree is still holding the leaves they'll still be broken. If the leaves are persistent (placed by player) they'll also be destroyed.
    # The radius is applied from one of the top most log blocks.
    # INFO: break_leaves must be activated for this to take effect.
    # INFO: Only in INSTANTANEOUS mode.
    # Min: 0
    # Max: 10
    I:leaves_breaking_force_radius=0

    # Additional list of blocks considered as leaves.
    # INFO: Blocks marked with the leaves tag will already be whitelisted.
    S:leaves_whitelisted <
     >

    # List of blocks that should not be considered as logs.
    # INFO: This wins over the whitelist.
    S:logs_blacklisted <
     >

    # The maximum size of a tree. If there's more logs than this value the tree won't be cut.
    # INFO: Only in INSTANTANEOUS mode.
    # Min: 1
    # Max: 2147483647
    I:logs_max_count=100

    # Additional list of blocks considered as logs and that will be destroyed by the mod.
    # INFO: Blocks marked with the log tag will already be whitelisted.
    S:logs_whitelisted <
     >

    # The minimum amount of leaves that needs to be around the top most log in order for the mod to consider it a tree.
    # INFO: Only in INSTANTANEOUS mode.
    # Min: 0
    # Max: 5
    I:minimum_leaves_around_required=0
}
```

**Comment by Rakambda** [comment]
Hello,
I'm not too sure what you mean by "I would like the blocks to fall as a whole instead of destroying and dropping items or destroying them from below".

For the `break_order=LOWEST_FIRST` configuration, it doesn't exists in 1.12.2 and was introduced in later versions of the mod (for newer minecraft versions).

**Comment by Shifty-Nifty** [comment]
Hello I have used this on my PC and it has worked fine. So I decided to try this mod on my steam deck using prism, I made sure I downloaded the correct versions of Minecraft Java and the falling tree 1.20.1, it does not seem to work when I cut down trees.

Am I doing something different incorrectly?

**Comment by Rakambda** [comment]
Hello, with just that info I cannot really say much.
Can you share your `logs/debug.log` / `logs/latest.log`.

**Comment by Shifty-Nifty** [comment]
ok i will try and locate the log and get back to you.
________________________________

**Comment by Shifty-Nifty** [comment]
here are the logs
________________________________

**Comment by Rakambda** [comment]
If you tried to put an attachment in the mail response, i don't think it's supported.

**Comment by Shifty-Nifty** [comment]
Ok, the main debug log is very long.

The latest log:


[05Feb2024 14:51:52.370] [Render thread/INFO] [Controllable/]: Applying gamepad mappings from internal database
[05Feb2024 14:51:52.381] [Render thread/INFO] [Controllable/]: Successfully updated 1 gamepad mappings
[05Feb2024 14:51:52.426] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
[05Feb2024 14:51:52.426] [Render thread/INFO] [fr.rakambda.fallingtree.common.network.PacketUtils/]: Disconnected from server, resetting proxy config values


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Shifty-Nifty** [comment]
Debug.log


[05Feb2024 14:51:52.370] [Render thread/INFO] [Controllable/]: Applying gamepad mappings from internal database
[05Feb2024 14:51:52.381] [Render thread/INFO] [Controllable/]: Successfully updated 1 gamepad mappings
[05Feb2024 14:51:52.426] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
[05Feb2024 14:51:52.426] [Render thread/INFO] [fr.rakambda.fallingtree.common.network.PacketUtils/]: Disconnected from server, resetting proxy config values


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Rakambda** [comment]
There doesn't seem to be anything weird. I don't really know what's going on.
The usual things are :
* If playing on a server, mod has to be server side
* Check if the enchantements are enabled in the config, if so then gotta have an axe enchanted with it
