### ISSUE TITLE
Speed multiplicand not affecting tree breaking speed

### ISSUE THREAD

**Issue by aditqo** [RakambdaOrg/FallingTree#69]
**Describe the bug**
Changing the "Speed multiplicand" does not affect the tree breaking speed. Seems to be stuck at 0

**To Reproduce**
1.  Changed speed multiplicand via the client mod menu ( trees still break at speed 0 )
2.  Changed speed multiplicand in the config file ( trees still break at speed 0 )

**Infos:**
 - Minecraft verson: [e.g. 1.16.5]
 - Mod loader: [Forge - version 36.0.1] also tested with 36.0.15
 - Mod version: [2.10.0]

**Comment by Rakambda** [comment]
In singleplayer or multiplayer?

**Comment by aditqo** [comment]
This was in single player with other mods installed

I deleted config from all mods and after restarting it seems to be fine. Maybe a different mod was causing this issue. Sorry for false alarm.
