### ISSUE TITLE
Leaf Decay Sound

### ISSUE THREAD

**Issue by saintkief** [RakambdaOrg/FallingTree#7]
With leaf break active, the collective block breaking sound can be deafening. If there's a way to mitigate how loud leaf decay is, that would be great :)

**Comment by Rakambda** [comment]
I can't really remove the sound itself (controlled by the "Block" sound option). Though I can add some sort of random delay in the breaking to avoid having all the leaves breaking at the same time.

What do you think of it?

**Comment by saintkief** [comment]
That would be great! Merely a suggestion since turning down the block sound option renders all other blocks too quiet while leaf decay sounds like 100% on 5% block volume.

**Comment by Rakambda** [comment]
Are you on the latest version?
I actually tried to look a bit into it and even with all the sounds on, the leaves breaking makes no sound.
Perhaps you're talking about the leaves that are forced to be broken? (with the defined radius)
