### ISSUE TITLE
Cut trees from branches towards cut point

### ISSUE THREAD

**Issue by Dramegno** [RakambdaOrg/FallingTree#71]
A config option for a hybrid mode between Instantaneous and Shift Down modes.

Basically what I am talking about here is that after the tool breaks/1 durability shift down the rest of the tree. This should 'cut' down the number of floating trees, and provide a solution that doesn't involve an insane amount of time cutting down a forest in Shift Down mode or nerdpoles. This will really help cut out the grind in regards to clearing forests involving larger trees that tend to interconnect.

**Comment by Rakambda** [comment]
I'm not really sure what would be the point of activating that for tool break/1 durability. If the tool is broken, well, you don't have any uses of it left. And if there's 1 durability left it'll cut just 1...

Though if we don't take into account these cases, the idea of an hybrid mode can be interesting. Basically trying to cut it in INSTANTANEOUS_MODE and if it reaches the max limit, cut with SHIFT_DOWN. This could as you say maybe improve the use in dense forests. Shift down would go cut the furthest log, and when the tree is isolated, it'll be cut instantaneously.
Though if the trees are connected at their base, it may not help that much.

**Comment by Dramegno** [comment]
what I was talking about is situations like say you have a tree that happens to have 100 logs and you cut it in instantaneous mode, and the axe runs out of usable durability after say 50 logs you now have a floating tree that is super annoying to get rid of since it appears that the logs that are chosen to be broken are random, thus creating lots of orphaned branches/sections that have to be hunted down individually using nerd poles/scaffolding to cut down the rest with a fresh/repaired axe. Now, with shift down, there aren't any orphaned sections created or at least any that I have experienced, but then I have to set there holding down the mouse button for long periods of time at least when cutting down a bunch of large trees gets mind-numbing after a while and is frankly pretty boring unless I get visited by a random creeper or something.
now I admit that this use case is most likely not very common but it is annoying when it appears. To give a peek into my current use case I have ~85 full stacks of logs from clearing out a section for my base and I am about 1/2 to 3/4 of the way there.

**Comment by Rakambda** [comment]
Yeah the behaviors are different. Insta will break them going from the cut point towards the furthest block. Shift down will do the opposite (cut the furthest).

I'll try to do an hybrid mod and let you test it to see if that solves your problem. You use fabric or forge?

**Comment by Dramegno** [comment]
I use forge. The thing is that in my observations Instanious mode does not go from closest to farthest but instead the log is chosen randomly with a slight weight on closer ones. I have attached an example of what I am talking about I used a vanilla Minecraft wooden axe and Jungle tree for this.
![Tree -Before](https://user-images.githubusercontent.com/33284290/108100403-e0bcd400-7053-11eb-9d80-b8b7f93ba826.png)
![Tree - After](https://user-images.githubusercontent.com/33284290/108100410-e31f2e00-7053-11eb-9219-22014eded492.png)

**Comment by Rakambda** [comment]
Okay I get a bit more what the problem is with the screenshot. I thought it was cutting it a bit more "cleanly" 😆 

https://www.dropbox.com/s/neynazdlejzw5kr/FallingTree-Forge-1.16.5-2.10.1.jar?dl=0

I did a version where it'll break the furthest away first like in shift down. So I think your issue should be "solved". It'll just leave behind the trunk part if there isn't any tool uses left. You can then come back later with a repaired tool, and hit the same spot. It should still be interconnected so that the whole tree can fall.
A thing to be aware of is that if you use the "minimum leaves around required" then it'll probably bring problems. As the branches are now broken first, on the second cut it's possible that the trunk is without leaves, and so it isn't cut.

Now that doesn't solve the "make an hybrid mode for when the max count is reached".  Will need more time to do the hybrid as I'll need to move a bit things internally for that.

**Comment by Dramegno** [comment]
It works wonderfully, this is what I imagined when I originally thought up a hybrid mode. I do see your point about the Minimum leaves setting but I would say that in the worst case of clearing a log pillar by hand is a lot less annoying and safer than hunting down orphaned logs 20+ blocks up.

**Comment by Rakambda** [comment]
If that matches what you thought about then I'll push that as a fix.

If one day someone is interested by that hybrid mode, another issue can be done and details for it discussed.
