### ISSUE TITLE
incorrect message in chat

### ISSUE THREAD

**Issue by pjlasl** [RakambdaOrg/FallingTree#72]
**Describe the bug**
When I attempt to chop down a tree that is too big, the following message is displayed in chat:

chat.fallingtree.tree_too_big

**To Reproduce**
1. chop down a large tree

**Infos:**
 - Minecraft verson: [e.g. 1.16.5]
 - Mod loader: [Fabric]
 - Mod version: [FallingTree-Fabric-1.16.5-2.10.2]

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

**Comment by Rakambda** [comment]
Hmm I can't reproduce. Downloaded the mod from CurseForge and the message displays fine:
![image](https://user-images.githubusercontent.com/1688389/108631084-94fd9680-7468-11eb-8769-4cff62d99ebf.png)

**Comment by pjlasl** [comment]
I only have the mod installed on my server. I don't have it on the client, could that be why?

**Comment by Rakambda** [comment]
Ah yeah. The translation files are inside the mod itself and not sent between client/server as only the client uses it to display the language (only the client knows its language).
Either you need the mod client side, or you can get the lang file itself and add it as part of a resourcepack if you don't want the mod itself client side.
