### ISSUE TITLE
Not working at server

### ISSUE THREAD

**Issue by GuilhermeUFF** [RakambdaOrg/FallingTree#722]
### Describe the bug

I got the mod installed both client and server side. At singleplayer worlds the mod work as intended. At multiplayer though, it simply doesnt work, like I haven't installed the mod. Already got Cloth Config API and Mod Menu installed.

### Minecraft version

1.21

### Fabric API version

0.100.4

### Mod version

1.21.0.5

### Configuration

```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxLeafDistanceFromLog": 15,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "breakMangroveRoots": true,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL",
    "spawnItemsAtBreakPoint": false
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0,
    "forceToolUsage": false
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "requireEnchantment": false
  },
  "sneakMode": "IGNORE",
  "breakInCreative": true,
  "lootInCreative": true,
  "notificationMode": "ACTION_BAR"
}
```

**Comment by Rakambda** [comment]
Please provide server logs.

**Comment by GuilhermeUFF** [comment]
[2024-07-01-6.log](https://github.com/user-attachments/files/16071126/2024-07-01-6.log)
Of course, here.

**Comment by Rakambda** [comment]
Fabric seems to not be intalled on the server, so no mods will load.

**Comment by GuilhermeUFF** [comment]
I don't think this really makes sense. The server is created through the fabric jar file. It even has a .fabric folder
![image](https://github.com/RakambdaOrg/FallingTree/assets/172866806/6d59cc72-e988-4bae-8bf1-9e33196ea0e2)

**Comment by Rakambda** [comment]
There's no mention of fabric at all in the logs, that seems weird. Can try with another mod, it shouldn't be loaded either.
