### ISSUE TITLE
Option for requiring non peristent leaves to cut a tree

### ISSUE THREAD

**Issue by VanJackal** [RakambdaOrg/FallingTree#723]
### Describe the feature

Non-persistent leaves are only generated by actual trees so this would be a way to make the mod only work on actual trees.

**Comment by VanJackal** [comment]
seems this feature is already a thing, it might be missing from the wiki though.

**Comment by Rakambda** [comment]
Indeed wasn't in the wiki. Added it.
JSON key is `trees.includePersistentLeavesInRequiredCount=false`.
