### ISSUE TITLE
got mod working in single but not realm

### ISSUE THREAD

**Issue by mramerica36** [RakambdaOrg/FallingTree#745]
### Describe the bug

So i installed forge, falling tree, and cloth config onto a backup of my realm and tried all 3 on single player. work like intended but once a restored the backup onto the realm. the mods just didn't work. they showed installed but the trees were not coming down. please help. I'm running default from the installer.

### Minecraft version

1.21.1

### Forge version

52.0.8

### Mod version

1.21.1.1

### Configuration

```json
unable to get/read
```

**Comment by Rakambda** [comment]
If the server is a "realm" then it is not possible to have it work.
This mod is server sided, and installing Forge/Fabric is not possible on realms.

**Comment by mramerica36** [comment]
good to know thanks
