### ISSUE TITLE
Unable to run on a 1.21.1 java server

### ISSUE THREAD

**Issue by 500ke30** [RakambdaOrg/FallingTree#750]
### Describe the bug

I can't for the life of me get this mod to work on my server that I run for me and my brothers. I've installed it client side only, server side only and both along with the dependency of the Fabric API. 

### Minecraft version

1.21.1

### Fabric API version

0.102.1

### Mod version

1.21.1

### Configuration

```json
I'm not sure where to find this. All I have is the .jar file that is in my client side mods folder.
```

**Comment by Obsolet3** [comment]
When I changed the name of the field in "enchantment" in the configuration file from "requireEnchantment" to "requireEnchant" the modification works but after starting the server another process overwrites the file, as a result the field name is back to "requireEnchantment".

Minecraft version: 1.21.1
NeoForge version: 21.0.167
Mod version: 1.21-1.21.0.7

**Comment by Rakambda** [comment]
Please provide the logs. It is in the `logs` folder inside the server.

**Comment by Obsolet3** [comment]
[latest.log](https://github.com/user-attachments/files/17439640/latest.log)

**Comment by Rakambda** [comment]
Logs seems to be fine.
What did you try to do? Cut a vanilla tree with a vanilla axe ?

**Comment by Obsolet3** [comment]
Yes, I tested it with vanilla objects.

The issue was with the field's value, not its name. So, even after a server restart, `"requireEnchantment": false` continues to work. However, when the value is true, it doesn't work because the Chopper enchantment is missing. I couldn't find this one. The example configuration file does not contain the registerEnchant flag, so my config does not either.

**Comment by Obsolet3** [comment]
My version of Valhelsia lacks the FallingTree Enchantments mod, which is probably why it didn't work with the flag set to true.

**Comment by Rakambda** [comment]
With 1.21+ enchants are added through a [FallingTree Enchantment **datapack**](https://www.curseforge.com/minecraft/data-packs/fallingtree-enchantments), this is not a mod.

**Comment by Rakambda** [comment]
Datapacks are installed inside your world, and not really "globally" on the server : https://minecraft.fandom.com/wiki/Tutorials/Installing_a_data_pack#Multiplayer

**Comment by Obsolet3** [comment]
Yes, I checked the world data and there were no files from falling tree enchantments. Thank you for having a look at that and useful links
