### ISSUE TITLE
Game crashes upon launch. Will not start.

### ISSUE THREAD

**Issue by notbrycem** [RakambdaOrg/FallingTree#765]
### Describe the bug

Receiving the following error when starting the game. 

The game crashed whilst bootstrap
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3218 failed

### Minecraft version

1.21.2

### Fabric API version

0.16.7

### Mod version

1.21.2.1

### Configuration

N/a (Config does not populate.)

### Relevant log output

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!
Time: 2024-10-23 03:35:45
Description: Bootstrap
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3218 failed
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
at knot//net.minecraft.class_2966.method_12851(class_2966.java:53)
at knot//net.minecraft.client.main.Main.main(Main.java:138)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fallingtree.mixins.json:LevelMixin from mod fallingtree] from phase [DEFAULT] in config [fallingtree.mixins.json] FAILED during APPLY
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on fallingtree.mixins.json:LevelMixin from mod fallingtree-
>@Inject::updateNeighborsExcept(Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;Lnet/minecraft/class_2350;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;Lnet/minecraft/class_2350;Lnet/minecraft/class_9904;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;Lnet/minecraft/class_2350;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT_APPLY Applicator Phase -> fallingtree.mixins.json:LevelMixin from mod fallingtree -> Apply Injections -> -> Inject -> fallingtree.mixins.json:LevelMixin from mod fallingtree->@Inject::updateNeighborsExcept(Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;Lnet/minecraft/class_2350;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:560)
at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:490)
at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:284)
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:508)
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1483)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
... 12 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: main
Stacktrace:
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(K
notClassDelegate.java:427)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
at knot//net.minecraft.class_2966.method_12851(class_2966.java:53)
-- Initialization --
Details:
Modules:
ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
DPAPI.DLL:Data Protection API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
GDI32.dll:GDI Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
POWRPROF.dll:Power Profile Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft
Corporation
SHELL32.dll:Windows Shell Common Dll:10.0.22621.4249 (WinBuild.160101.0800):Microsoft Corporation
SSPICLI.DLL:Security Support Provider Interface:10.0.22621.3810 (WinBuild.160101.0800):Microsoft Corporation
Secur32.dll:Security Support Provider Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
VCRUNTIME140.dll:MicrosoftÂ® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
apphelp.dll:Application Compatibility Client Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
awt.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.4317 (WinBuild.160101.0800):Microsoft Corporation
clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
com_antivirus.dll:Kaspersky ComAntivirus Component:30.1719.0.1010:AO Kaspersky Lab
combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
dxcore.dll:DXCore:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
gdi32full.dll:GDI Client DLL:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
javaw.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
jemalloc.dll
jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
jna16883331993882420784.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
kernel.appcore.dll:AppModel API Host:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
lwjgl.dll
management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
msvcp140.dll:MicrosoftÂ® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
msvcp_win.dll:MicrosoftÂ® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
ntdll.dll:NT Layer DLL:10.0.22621.4249 (WinBuild.160101.0800):Microsoft Corporation
perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
profapi.dll:User Profile Basic API:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
sunmscapi.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
ucrtbase.dll:MicrosoftÂ® C Runtime Library:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
vcruntime140_1.dll:MicrosoftÂ® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
win32u.dll:Win32u:10.0.22621.4317 (WinBuild.160101.0800):Microsoft Corporation
windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
Stacktrace:
at knot//net.minecraft.client.main.Main.main(Main.java:138)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-- System Details --
Details:
Minecraft Version: 1.21.2
Minecraft Version ID: 1.21.2
Operating System: Windows 11 (amd64) version 10.0
Java Version: 21.0.3, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 229821312 bytes (219 MiB) / 469762048 bytes (448 MiB) up to 4294967296 bytes (4096 MiB)
CPUs: 16
Processor Vendor: GenuineIntel
Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
Identifier: Intel64 Family 6 Model 154 Stepping 3
Microarchitecture: Alder Lake
Frequency (GHz): 3.11
Number of physical packages: 1
Number of physical CPUs: 12
Number of logical CPUs: 16
Graphics card #0 name: NVIDIA GeForce RTX 4060 Laptop GPU
Graphics card #0 vendor: NVIDIA
Graphics card #0 VRAM (MiB): 8188.00
Graphics card #0 deviceId: VideoController1
Graphics card #0 versionInfo: 32.0.15.6109
Graphics card #1 name: Intel(R) UHD Graphics
Graphics card #1 vendor: Intel Corporation
Graphics card #1 VRAM (MiB): 128.00
Graphics card #1 deviceId: VideoController2
Graphics card #1 versionInfo: 31.0.101.5333
Memory slot #0 capacity (MiB): 8192.00
Memory slot #0 clockSpeed (GHz): 3.20
Memory slot #0 type: DDR4
Virtual memory max (MiB): 20712.49
Virtual memory used (MiB): 9107.95
Swap memory total (MiB): 12800.00
Swap memory used (MiB): 358.18
Space in storage for jna.tmpdir (MiB): available: 82478.23, total: 471802.00
Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 82478.23, total: 471802.00
Space in storage for io.netty.native.workdir (MiB): available: 82478.23, total: 471802.00
Space in storage for java.io.tmpdir (MiB): available: 82478.23, total: 471802.00
Space in storage for workdir (MiB): available: 82478.23, total: 471802.00
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Fabric Mods:
architectury: Architectury 14.0.3
badoptimizations: BadOptimizations 2.2.0
better_craftables: Better Craftables 2.1.0
camerautils: Camera Utils 1.21.2-1.0.16
fabric-api-base: Fabric API Base 0.4.48+c47b9d4373
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4373
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1)
2.3.22+c47b9d4373
fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.5+c47b9d4373
capes: Capes 1.5.4+1.21.2
cloth-config: Cloth Config v16 16.0.141
cloth-basic-math: cloth-basic-math 0.6.1
combatedit: CombatEdit 2.0.5+1.21.2
fabric-command-api-v2: Fabric Command API (v2) 2.2.35+c47b9d4373
dark-loading-screen: Dark Loading Screen 1.6.15
detailab: Detail Armor Bar 2.6.3+1.21.2-fabric
euphoria_patcher: Euphoria Patcher 1.4.1-r5.3-fabric
io_sigpipe_jbsdiff: jbsdiff 1.0
extremesoundmuffler: Extreme Sound Muffler 3.48.2
fiber: fiber 0.23.0-2
fabric-api: Fabric API 0.106.1+1.21.2
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.78+c47b9d4373
fabric-biome-api-v1: Fabric Biome API (v1) 14.0.5+c47b9d4373
fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4373
fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4373
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.2+c47b9d4373
fabric-client-tags-api-v1: Fabric Client Tags 1.1.22+c47b9d4373
fabric-command-api-v1: Fabric Command API (v1) 1.2.56+f71b366f73
fabric-commands-v0: Fabric Commands (v0) 0.2.73+df3654b373
fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.5+c47b9d4373
fabric-convention-tags-v1: Fabric Convention Tags 2.1.0+7f945d5b73
fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.0+c47b9d4373
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4373
fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.38+c47b9d4373
fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.14+c47b9d4373
fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4373
fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.5+c47b9d4373
fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.9+c47b9d4373
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4373
fabric-item-api-v1: Fabric Item API (v1) 11.1.5+c47b9d4373
fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.15+e7c9ab6673
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b373
fabric-loot-api-v2: Fabric Loot API (v2) 3.0.24+3f89f5a573
fabric-loot-api-v3: Fabric Loot API (v3) 1.0.12+c47b9d4373
fabric-message-api-v1: Fabric Message API (v1) 6.0.19+c47b9d4373
fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.7+c47b9d4373
fabric-networking-api-v1: Fabric Networking API (v1) 4.3.3+56ec7ac673
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.7+c47b9d4373
fabric-particles-v1: Fabric Particles (v1) 4.0.8+c47b9d4373
fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.2+c47b9d4373
fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+56ec7ac673
fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.3+c47b9d4373
fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.3+c47b9d4373
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e73
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.13+c47b9d4373
fabric-rendering-v0: Fabric Rendering (v0) 1.1.81+df3654b373
fabric-rendering-v1: Fabric Rendering (v1) 8.0.5+c47b9d4373
fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4373
fabric-screen-api-v1: Fabric Screen API (v1) 2.0.32+c47b9d4373
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.98+c47b9d4373
fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4373
fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+c47b9d4373
fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4373
fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
fabricloader: Fabric Loader 0.16.7
mixinextras: MixinExtras 0.4.1
fallingtree: FallingTree 1.21.2.1
iris: Iris 1.8.0-beta.6+mc1.21.2
io_github_douira_glsl-transformer: glsl-transformer 2.0.1
org_anarres_jcpp: jcpp 1.4.14
org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
jade: Jade 16.0.0+fabric
java: OpenJDK 64-Bit Server VM 21
ksyxis: Ksyxis 1.3.2
lithostitched: Lithostitched 1.3.1a
minecraft: Minecraft 1.21.2
modmenu: Mod Menu 12.0.0-beta.1
moreculling: More Culling 1.1.0-beta.1
conditional-mixin: conditional mixin 0.6.3
mixinsquared: MixinSquared 0.2.0
mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.5
mr_dungeons_andtavernsancientcityoverhaul: Dungeons and Taverns Ancient City Overhaul 1-v2.1
mr_dungeons_andtavernsnetherfortressoverhaul: Dungeons and Taverns Nether Fortress Overhaul 1-v2.5
mr_dungeons_andtavernspillageroutpostoverhaul: Dungeons and Taverns Pillager Outpost Overhaul 1-v3
mr_dungeons_andtavernsstrongholdoverhaul: Dungeons and Taverns Stronghold Overhaul 1-v2.2
mr_dungeons_andtavernsswamphutoverhaul: Dungeons and Taverns Swamp Hut Overhaul 1-v2.1
mr_dungeons_andtavernswoodlandmansionreplacement: Dungeons and Taverns Woodland Mansion Replacement 1-v1.3
musicnotification: Music Notification 2.2.0
particletweaks: Particle Tweaks 1.2.2-mc1.21.2-rc2
simple_copper_pipes: Simple Copper Pipes 2.0.1
frozenlib: FrozenLib 1.9-mc1.21.2-rc2
sodium: Sodium 0.6.0-beta.3+mc1.21.2
status-effect-bars: Status Effect Bars 1.0.7
universal-graves: Universal Graves 3.5.0+1.21.2
common-protection-api: Common Protection API 1.0.0
fabric-permissions-api-v0: fabric-permissions-api 0.3.2-SNAPSHOT
placeholder-api: Placeholder API 2.5.0+1.21.2
polymer-core: Polymer (Core) 0.10.0+1.21.2
polymer-networking: Polymer (Networking) 0.10.0+1.21.2
polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.10.0+1.21.2
polymer-resource-pack: Polymer (Resource Pack) 0.10.0+1.21.2
polymer-virtual-entity: Polymer (Virtual Entity) 0.10.0+1.21.2
polymer-common: Polymer (Common) 0.10.0+1.21.2
predicate-api: Predicate API 0.6.0+1.21.2
server_translations_api: Server Translations API 2.4.0+1.21.2-rc1
packet_tweaker: Packet Tweaker 0.6.0-pre.1+1.21.2-pre3
sgui: sgui 1.7.1+1.21.2
voxelmap: Voxelmap 1.21.2-1.14
yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
com_twelvemonkeys_common_common-image: common-image 3.10.0
com_twelvemonkeys_common_common-io: common-io 3.10.0
com_twelvemonkeys_common_common-lang: common-lang 3.10.0
com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
org_quiltmc_parsers_gson: gson 0.2.1
org_quiltmc_parsers_json: json 0.2.1
Launched Version: fabric-loader-0.16.7-1.21.2
Launcher name: minecraft-launcher
Backend library: LWJGL version 3.3.3-snapshot
Backend API: Unknown
Window size: <not initialized>
GFLW Platform: <error>
GL Caps: ERR
GL debug messages: <disabled>
Is Modded: Definitely; Client brand changed to 'fabric'
Universe: 404
Type: Client (map_client.txt)
Locale: en_CA
System encoding: Cp1252
File encoding: UTF-8
CPU: <unknown>

**Comment by Rakambda** [comment]
What about with this build ? (you can fidn the mod inside a zip fiel at the bottom of the page)
https://github.com/RakambdaOrg/FallingTree/actions/runs/11480631108
