### ISSUE TITLE
Trees are not detected on Forge 1.21.3

### ISSUE THREAD

**Issue by Impor9** [RakambdaOrg/FallingTree#769]
### Describe the bug

The mode doesn't work.

### Minecraft version

1.21.3

### Forge version

53.0.7

### Mod version

1.21.3-1.21.3.2

### Configuration

.

**Comment by Rakambda** [comment]
Issue is here https://github.com/RakambdaOrg/FallingTree/blob/minecraft/1.21.3/forge/src/main/java/fr/rakambda/fallingtree/forge/common/FallingTreeCommonsImpl.java#L217, when asking forge for the blocks that are tagged as logs, it gives nothing back.

Editing the configuration to add each log one by one should solve the issue in the meantime.
As forge is still quite new on this version and things are often broken at first, I'll wait a bit to see if forges fixes that or if their API somehow changes.
