### ISSUE TITLE
Falling Tree

### ISSUE THREAD

**Issue by WyldsKaitlyn** [RakambdaOrg/FallingTree#8]
My brother and I were looking for a mod like this for ages now and we finally found one until we got on and saw it didn't work. We checked all the settings but nothing worked. If we had to rate it out of stars I would give it a 1 out of 5 because the false advertising was on point it made you believe it was going to work.

**Comment by Rakambda** [comment]
Then if it doesn't work, do you even have a `crash-report` (crash report folder) or `debug.log` (logs folder) file to provide?
Without those it's pretty much impossible to diagnose the error.
