### ISSUE TITLE
"Secure mod features disabled, update JDK" Trees do not fall

### ISSUE THREAD

**Issue by bur8ver** [RakambdaOrg/FallingTree#81]
The mod does not do anything even though it is in the mods folder. The screen says:
```
Falling Tree
Version: 2.11.0
ModID: fallingtree State:done
No child mods found
License: GPL-3.0

Change the way you cut trees.

**Secure mod features disabled, update JDK**
``` 

 - Minecraft verson: [e.g. 1.14.4]
 - Mod loader: [Forge]
 - Mod version: [2.11.0]

Imgur link to pictures: https://imgur.com/a/p9pdO0G

Please tell me if I did something wrong when installing this mod. If I didn't install it wrong I hope this issue can be fixed soon. Thank you for reading,
![Screen Shot 2021-04-04 at 8 27 58 PM](https://user-images.githubusercontent.com/82116752/113918754-a8a25980-9797-11eb-9bbf-1c1db13ff2c6.png)

**Comment by Rakambda** [comment]
This isn't a mod issue.

This is forge telling you to upgrade your JDK to use it.
What version of Java do you have (can be seen in the F3 menu while in game) ?

If this is less than 1.8_281 then you're not up to date.
Download can be found here: https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

Edit: 
Another way:
![image](https://user-images.githubusercontent.com/1688389/113920066-98649b80-97e4-11eb-8176-db535df58480.png)

**Comment by Rakambda** [comment]
For reference: https://github.com/cpw/modlauncher/blob/master/src/main/java/cpw/mods/modlauncher/api/IEnvironment.java#L117

**Comment by Rakambda** [comment]
Well it happens for me too, I'll look a bit more into it. Though the message of the "Secure mod disabled" shouldn't cause any issues and the mod should run fine.

**Comment by Rakambda** [comment]
To remove the "Secure" message, you have to have a not super mega old version of Java and, this is important, tell the Minecraft launcher to use it. By default the launcher uses a Java version that is bundled with it and that is super old. You can probably search online how to change the minecraft version used but essentially:

![image](https://user-images.githubusercontent.com/1688389/113921885-e084bd80-97e6-11eb-822d-296c0e215122.png)

(you can even use Java 11 instead of Java 8 if you want to be on the latest LTS version)

But again this is just to remove the message that is just here as information. This won't prevent you from using the mod.

**Comment by bur8ver** [comment]
Hello, thanks for answering. I see the picture of you using the configure Java app. I am on an iMac so I had to do it a bit differently. It says that I have Java 8 Update 281. I think that is up to date. When I tried punching trees in creative and survival they didn't fall and I couldn't use the mod.

I will try searching online to see how to change the version of java that Minecraft uses.

![Screen Shot 2021-04-07 at 12 19 21 PM](https://user-images.githubusercontent.com/82116752/113921950-8ad6f380-979b-11eb-84d7-01fc6cb0f7bb.png)

**Comment by Rakambda** [comment]
Your java seems "up to date", at least recent enough. Just that minecraft doesn't use it to run minecraft.

As I said the mod should work fine even with the "secure" message displayed.

The thing is:
* To break trees in creative, you need to update the configuration to allow it to do so.
* To break trees in general, you need a tool (axes by default)

**Comment by Rakambda** [comment]
If you do the change in the profile of your minecraft installation to set your own java (https://github.com/RakSrinaNa/FallingTree/issues/81#issuecomment-815163661), it should ressemble something like ` /Library/Java/JavaVirtualMachines/jdk-8 ....` on osx.

**Comment by bur8ver** [comment]
I'll get back to you once I figure this out. Thanks for helping.

**Comment by Rakambda** [comment]
Jar is now signed. Won't change anything on how it works but i'll display signature information if a not too old java is used (other than the bundle one).
