### ISSUE TITLE
Tinker's Construct Compatibility

### ISSUE THREAD

**Issue by Ofimofii** [RakambdaOrg/FallingTree#97]
I love the mod the only problem I have is that it does not work with 1.16.5 Tinker's.

**Comment by Rakambda** [comment]
What exactly does not work?

Whitelisting `tconstruct:axe` allows me to use it perfectly fine:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1688389/115894232-50d34600-a459-11eb-9827-63820e7b3603.gif)

**Comment by pirahtays** [comment]
@RakSrinaNa - Is this the correct way of doing this for the forge mod?  Because it doesn't seem to be working for me
```
[tools]
	#INFO: Items marked with the axe tag will already be whitelisted.
	whitelisted = ["tconstruct:axe"]
```

**Comment by Rakambda** [comment]
Yeah That should be the way. Though edit the setting file while Minecraft if not launched or use the in-game GUI.

If it doesn't work try to post your full config in a new issue and I'll try to replicate it.

**Comment by pirahtays** [comment]
It did not, but I figured it out.  Might be a new change in tinkers but it appears you need to specify 
`whitelisted = ["tconstruct:hand_axe", "tconstruct:broad_axe"]`
