### ISSUE TITLE
Forge 36.1.10+ doesn't load mod

### ISSUE THREAD

**Issue by Rakambda** [RakambdaOrg/FallingTree#98]
**Describe the bug**
Mod doesn't load and displays message 
```
Mod fallingtree only supports cloth-config
Currently, cloth-config is 4.11.19
```

Forge 36.1.4 doesn't have this problem.

**To Reproduce**
1. Start Minecraft with the given versions

**Infos:**
 - Minecraft version: 1.16.5
 - Mod version: 2.11.1
 - Forge version: 36.1.12

**Comment by Rakambda** [comment]
Changes from https://github.com/MinecraftForge/MinecraftForge/issues/7696 seems to now require a version range to be set for dependencies.
Fixed with 3340e0d66d296590141d1e087e3d768d94ed985a

**Comment by ZEkA10000** [comment]
So... 
I have forge 36.1.32
With Falling tree v2.11.1 i got this error: `Mod fallingtree only supports cloth-config. Currently. cloth-config is 4.11.26`
With newer version of Falling tree I get minecraft chashes (even Not Enough Crashes don't helps me)

**Comment by Rakambda** [comment]
Look the milestone this issue is attached to... This is fixed in 2.11.2. So either you have to update the mod, or use a forge version previous to 36.1.10.

**Comment by ZEkA10000** [comment]
I got it. Minecraft crashes with new versions of Falling Tree because it has conflict with OffHand Combat mod.
I just deleted OffHand Combat mod and without errors.

**Comment by ZEkA10000** [comment]
Lmao. In v2.11.5 mod forgot how to break trees.

**Comment by Rakambda** [comment]
If you have an issue with that version please open a different issue.
